SELECT DISTINCT A.nr_SeguradoCPFCNPJ,A.nm_SeguradoNome
FROM tbBR_tab_AUTO_2016 AS A
INNER JOIN ( VALUES ('ANGELA MONTEIRO SANTOS'),('ANGELA TAVARES') ) AS B(Nome)
	ON A.nm_SeguradoNome = B.Nome	


SELECT DISTINCT 
	A.nr_SeguradoCPFCNPJ,A.nm_SeguradoNome,
	B.CPF,B.Nome
FROM tbBR_tab_AUTO_2016 AS A
	INNER JOIN ( 
		VALUES	('JOSE AFONSO FILHO',39355543891),
				('PAULO CESAR REDONDO',5840882801),
				('DILMA TERESINHA BOBATO A DOS SANTOS',22269070925),
				('SABRINA APARECIDA GONCALVES',22218458896) 
		) AS B(Nome, CPF)
	ON A.nr_SeguradoCPFCNPJ = B.CPF