select	
	SUBSTRING(REPLACE(dados,';',''),	1		,1			) AS		MODALIDADE           
,	SUBSTRING(REPLACE(dados,';',''),	2		,4			) AS		CD_CIA               
,	SUBSTRING(REPLACE(dados,';',''),	6		,30			) AS		NM_CIA               
,	SUBSTRING(REPLACE(dados,';',''),	36		,3			) AS		CD_SUCURSAL          
,	SUBSTRING(REPLACE(dados,';',''),	39		,10			) AS		NR_PROPOSTA          
,	SUBSTRING(REPLACE(dados,';',''),	49		,4			) AS		NR_ITEM              
,	SUBSTRING(REPLACE(dados,';',''),	53		,1			) AS		TP_SISTEMA           
,	SUBSTRING(REPLACE(dados,';',''),	54		,2			) AS		CD_ORIGEM            
,	SUBSTRING(REPLACE(dados,';',''),	56		,4			) AS		CD_USUARIO           
,	SUBSTRING(REPLACE(dados,';',''),	60		,4			) AS		CD_CIA_RENOVA        
,	SUBSTRING(REPLACE(dados,';',''),	64		,5			) AS		CD_SUCURSAL_RENOVA   
,	SUBSTRING(REPLACE(dados,';',''),	69		,16			) AS		NR_APOLICE_RENOVA    
,	SUBSTRING(REPLACE(dados,';',''),	85		,5			) AS		NR_ITEM_RENOVA       
,	SUBSTRING(REPLACE(dados,';',''),	90		,4			) AS		CD_EMPRESA           
,	SUBSTRING(REPLACE(dados,';',''),	94		,4			) AS		CD_DEPTO             
,	SUBSTRING(REPLACE(dados,';',''),	98		,10			) AS		NR_MATRICULA         
,	SUBSTRING(REPLACE(dados,';',''),	108		,20			) AS		DS_PARENTESCO        
,	SUBSTRING(REPLACE(dados,';',''),	128		,40			) AS		NM_SEGURADO          
,	SUBSTRING(REPLACE(dados,';',''),	168		,8			) AS		DS_PESSOA            
,	SUBSTRING(REPLACE(dados,';',''),	176		,40			) AS		NM_ENDERECO          
,	SUBSTRING(REPLACE(dados,';',''),	216		,30			) AS		NM_BAIRRO            
,	SUBSTRING(REPLACE(dados,';',''),	246		,20			) AS		NM_MUNICIPIO         
,	SUBSTRING(REPLACE(dados,';',''),	266		,2			) AS		CD_ESTADO            
,	SUBSTRING(REPLACE(dados,';',''),	268		,8			) AS		NR_CEP               
,	SUBSTRING(REPLACE(dados,';',''),	276		,11			) AS		FILLER_VAGO          
,	SUBSTRING(REPLACE(dados,';',''),	287		,14			) AS		NR_CPF_CGC           
,	SUBSTRING(REPLACE(dados,';',''),	301		,40			) AS		NM_POR_CONTA_DE      
,	SUBSTRING(REPLACE(dados,';',''),	341		,10			) AS		DT_INICIO_VIGENCIA   
,	SUBSTRING(REPLACE(dados,';',''),	351		,10			) AS		DT_FINAL_VIGENCIA    
,	SUBSTRING(REPLACE(dados,';',''),	361		,40			) AS		NM_ENDERECO_RISCO    
,	SUBSTRING(REPLACE(dados,';',''),	401		,10			) AS		NM_COMPLEMENTO_RISCO 
,	SUBSTRING(REPLACE(dados,';',''),	411		,30			) AS		NM_BAIRRO_RISCO      
,	SUBSTRING(REPLACE(dados,';',''),	441		,20			) AS		NM_MUNICIPIO_RISCO   
,	SUBSTRING(REPLACE(dados,';',''),	461		,2			) AS		CD_ESTADO_RISCO      
,	SUBSTRING(REPLACE(dados,';',''),	463		,8			) AS		NR_CEP_RISCO         
,	SUBSTRING(REPLACE(dados,';',''),	471		,4			) AS		CD_VEICULO           
,	SUBSTRING(REPLACE(dados,';',''),	475		,40			) AS		DS_VEICULO           
,	SUBSTRING(REPLACE(dados,';',''),	515		,40			) AS		DS_FABRICANTE        
,	SUBSTRING(REPLACE(dados,';',''),	555		,7			) AS		NR_PLACA             
,	SUBSTRING(REPLACE(dados,';',''),	562		,22			) AS		NR_CHASSI            
,	SUBSTRING(REPLACE(dados,';',''),	584		,4			) AS		NR_ANO_FABRICACAO    
,	SUBSTRING(REPLACE(dados,';',''),	588		,4			) AS		NR_ANO_MODELO        
,	SUBSTRING(REPLACE(dados,';',''),	592		,15			) AS		DS_COMBUSTIVEL       
,	SUBSTRING(REPLACE(dados,';',''),	607		,2			) AS		NR_PORTAS            
,	SUBSTRING(REPLACE(dados,';',''),	609		,2			) AS		NR_EIXOS             
,	SUBSTRING(REPLACE(dados,';',''),	611		,15			) AS		DS_USO_VEICULO       
,	SUBSTRING(REPLACE(dados,';',''),	626		,4			) AS		CD_REGIAO_FENASEG    
,	SUBSTRING(REPLACE(dados,';',''),	630		,1			) AS		IN_SEM_OPCIONAIS     
,	SUBSTRING(REPLACE(dados,';',''),	631		,1			) AS		IN_AR                
,	SUBSTRING(REPLACE(dados,';',''),	632		,1			) AS		IN_DIRECAO           
,	SUBSTRING(REPLACE(dados,';',''),	633		,1			) AS		IN_CAMBIO_AUTOMATICO 
,	SUBSTRING(REPLACE(dados,';',''),	634		,1			) AS		IN_BANCO_COURO       
,	SUBSTRING(REPLACE(dados,';',''),	635		,1			) AS		IN_FREIO_ABS         
,	SUBSTRING(REPLACE(dados,';',''),	636		,1			) AS		IN_AIR_BAG           
,	SUBSTRING(REPLACE(dados,';',''),	637		,1			) AS		IN_CAMBIO_SEMI       
,	SUBSTRING(REPLACE(dados,';',''),	638		,1			) AS		IN_COMPREENSIVA      
,	SUBSTRING(REPLACE(dados,';',''),	639		,1			) AS		IN_INCENDIO_ROUBO    
,	SUBSTRING(REPLACE(dados,';',''),	640		,1			) AS		IN_RCF               
,	SUBSTRING(REPLACE(dados,';',''),	641		,1			) AS		IN_APP               
,	SUBSTRING(REPLACE(dados,';',''),	642		,1			) AS		IN_CARRO_RESERVA     
,	SUBSTRING(REPLACE(dados,';',''),	643		,1			) AS		IN_DIA_NOITE         
,	SUBSTRING(REPLACE(dados,';',''),	644		,1			) AS		IN_VIDRO             
,	SUBSTRING(REPLACE(dados,';',''),	645		,2			) AS		CD_CATEGORIA_AUTO    
,	SUBSTRING(REPLACE(dados,';',''),	647		,2			) AS		CD_CATEGORIA_RCF     
,	SUBSTRING(REPLACE(dados,';',''),	649		,1			) AS		IN_BONUS             
,	SUBSTRING(REPLACE(dados,';',''),	650		,3			) AS		FT_AJUSTE_VMR        
,	SUBSTRING(REPLACE(dados,';',''),	653		,9			) AS		VL_IS_CASCO          
,	SUBSTRING(REPLACE(dados,';',''),	662		,9			) AS		VL_DESP_EXTR         
,	SUBSTRING(REPLACE(dados,';',''),	671		,9			) AS		VL_IS_CARROCERIA     
,	SUBSTRING(REPLACE(dados,';',''),	680		,9			) AS		VL_IS_EQUIPAMENTO    
,	SUBSTRING(REPLACE(dados,';',''),	689		,9			) AS		VL_IS_ACESSORIO      
,	SUBSTRING(REPLACE(dados,';',''),	698		,8			) AS		VL_DIARIA_PARALIZ    
,	SUBSTRING(REPLACE(dados,';',''),	706		,10			) AS		CD_FIPE              
,	SUBSTRING(REPLACE(dados,';',''),	716		,9			) AS		VL_IS_DM             
,	SUBSTRING(REPLACE(dados,';',''),	725		,9			) AS		VL_IS_DP             
,	SUBSTRING(REPLACE(dados,';',''),	734		,9			) AS		VL_IS_DMO            
,	SUBSTRING(REPLACE(dados,';',''),	743		,9			) AS		VL_IS_GU             
,	SUBSTRING(REPLACE(dados,';',''),	752		,9			) AS		VL_IS_MORTE          
,	SUBSTRING(REPLACE(dados,';',''),	761		,9			) AS		VL_IS_INVALIDEZ      
,	SUBSTRING(REPLACE(dados,';',''),	770		,3			) AS		NR_PASSAGEIROS       
,	SUBSTRING(REPLACE(dados,';',''),	773		,8			) AS		VL_PREMIO_AUTO       
,	SUBSTRING(REPLACE(dados,';',''),	781		,1			) AS		PREM_AUTO_SINAL      
,	SUBSTRING(REPLACE(dados,';',''),	782		,8			) AS		VL_FRANQUIA_VIDRO    
,	SUBSTRING(REPLACE(dados,';',''),	790		,8			) AS		VL_FRANQUIA_CARROC   
,	SUBSTRING(REPLACE(dados,';',''),	798		,8			) AS		VL_FRANQUIA_EQUIP    
,	SUBSTRING(REPLACE(dados,';',''),	806		,8			) AS		VL_PREMIO_LIQUIDO    
,	SUBSTRING(REPLACE(dados,';',''),	814		,1			) AS		PREM_LIQ_SINAL       
,	SUBSTRING(REPLACE(dados,';',''),	815		,8			) AS		VL_CUSTO             
,	SUBSTRING(REPLACE(dados,';',''),	823		,8			) AS		VL_ADICIONAL_FRAC    
,	SUBSTRING(REPLACE(dados,';',''),	831		,8			) AS		VL_IOF               
,	SUBSTRING(REPLACE(dados,';',''),	839		,8			) AS		VL_PREMIO_TOTAL      
,	SUBSTRING(REPLACE(dados,';',''),	847		,1			) AS		PREM_TOT_SINAL       
,	SUBSTRING(REPLACE(dados,';',''),	848		,2			) AS		PC_TAXA_JUROS        
,	SUBSTRING(REPLACE(dados,';',''),	850		,8			) AS		VL_1A_PRESTACAO      
,	SUBSTRING(REPLACE(dados,';',''),	858		,2			) AS		QT_PRESTACAO_RESTANTE
,	SUBSTRING(REPLACE(dados,';',''),	860		,8			) AS		VL_DEMAIS_PREST      
,	SUBSTRING(REPLACE(dados,';',''),	868		,3			) AS		NR_CLAUSULA01        
,	SUBSTRING(REPLACE(dados,';',''),	871		,3			) AS		NR_CLAUSULA02        
,	SUBSTRING(REPLACE(dados,';',''),	874		,3			) AS		NR_CLAUSULA03        
,	SUBSTRING(REPLACE(dados,';',''),	877		,3			) AS		NR_CLAUSULA04        
,	SUBSTRING(REPLACE(dados,';',''),	880		,3			) AS		NR_CLAUSULA05        
,	SUBSTRING(REPLACE(dados,';',''),	883		,3			) AS		NR_CLAUSULA06        
,	SUBSTRING(REPLACE(dados,';',''),	886		,3			) AS		NR_CLAUSULA07        
,	SUBSTRING(REPLACE(dados,';',''),	889		,3			) AS		NR_CLAUSULA08        
,	SUBSTRING(REPLACE(dados,';',''),	892		,3			) AS		NR_CLAUSULA09        
,	SUBSTRING(REPLACE(dados,';',''),	895		,3			) AS		NR_CLAUSULA10        
,	SUBSTRING(REPLACE(dados,';',''),	898		,3			) AS		NR_CLAUSULA11        
,	SUBSTRING(REPLACE(dados,';',''),	901		,3			) AS		NR_CLAUSULA12        
,	SUBSTRING(REPLACE(dados,';',''),	904		,3			) AS		NR_CLAUSULA13        
,	SUBSTRING(REPLACE(dados,';',''),	907		,3			) AS		NR_CLAUSULA14        
,	SUBSTRING(REPLACE(dados,';',''),	910		,3			) AS		NR_CLAUSULA15        
,	SUBSTRING(REPLACE(dados,';',''),	913		,3			) AS		NR_CLAUSULA16        
,	SUBSTRING(REPLACE(dados,';',''),	916		,3			) AS		NR_CLAUSULA17        
,	SUBSTRING(REPLACE(dados,';',''),	919		,3			) AS		NR_CLAUSULA18        
,	SUBSTRING(REPLACE(dados,';',''),	922		,3			) AS		NR_CLAUSULA19        
,	SUBSTRING(REPLACE(dados,';',''),	925		,3			) AS		NR_CLAUSULA20        
,	SUBSTRING(REPLACE(dados,';',''),	928		,3			) AS		NR_CLAUSULA21        
,	SUBSTRING(REPLACE(dados,';',''),	931		,3			) AS		NR_CLAUSULA22        
,	SUBSTRING(REPLACE(dados,';',''),	934		,3			) AS		NR_CLAUSULA23        
,	SUBSTRING(REPLACE(dados,';',''),	937		,3			) AS		NR_CLAUSULA24        
,	SUBSTRING(REPLACE(dados,';',''),	940		,3			) AS		NR_CLAUSULA25        
,	SUBSTRING(REPLACE(dados,';',''),	943		,3			) AS		NR_CLAUSULA26        
,	SUBSTRING(REPLACE(dados,';',''),	946		,3			) AS		NR_CLAUSULA27        
,	SUBSTRING(REPLACE(dados,';',''),	949		,3			) AS		NR_CLAUSULA28        
,	SUBSTRING(REPLACE(dados,';',''),	952		,3			) AS		NR_CLAUSULA29        
,	SUBSTRING(REPLACE(dados,';',''),	955		,3			) AS		NR_CLAUSULA30        
,	SUBSTRING(REPLACE(dados,';',''),	958		,3			) AS		NR_CLAUSULA31        
,	SUBSTRING(REPLACE(dados,';',''),	961		,3			) AS		NR_CLAUSULA32        
,	SUBSTRING(REPLACE(dados,';',''),	964		,3			) AS		NR_CLAUSULA33        
,	SUBSTRING(REPLACE(dados,';',''),	967		,3			) AS		NR_CLAUSULA34        
,	SUBSTRING(REPLACE(dados,';',''),	970		,3			) AS		NR_CLAUSULA35        
,	SUBSTRING(REPLACE(dados,';',''),	973		,3			) AS		NR_CLAUSULA36        
,	SUBSTRING(REPLACE(dados,';',''),	976		,3			) AS		NR_CLAUSULA37        
,	SUBSTRING(REPLACE(dados,';',''),	979		,3			) AS		NR_CLAUSULA38        
,	SUBSTRING(REPLACE(dados,';',''),	982		,3			) AS		NR_CLAUSULA39        
,	SUBSTRING(REPLACE(dados,';',''),	985		,3			) AS		NR_CLAUSULA40        
,	SUBSTRING(REPLACE(dados,';',''),	988		,1			) AS		IN_CARNE             
,	SUBSTRING(REPLACE(dados,';',''),	989		,1			) AS		IN_DEBITO            
,	SUBSTRING(REPLACE(dados,';',''),	990		,4			) AS		NR_BANCO             
,	SUBSTRING(REPLACE(dados,';',''),	994		,9			) AS		NR_AGENCIA           
,	SUBSTRING(REPLACE(dados,';',''),	1003	,17			) AS		NR_CONTA             
,	SUBSTRING(REPLACE(dados,';',''),	1020	,3			) AS		PC_DESC_AUTO         
,	SUBSTRING(REPLACE(dados,';',''),	1023	,3			) AS		PC_DESC_RCF          
,	SUBSTRING(REPLACE(dados,';',''),	1026	,3			) AS		PC_DESC_APP          
,	SUBSTRING(REPLACE(dados,';',''),	1029	,11			) AS		NR_CCB               
,	SUBSTRING(REPLACE(dados,';',''),	1040	,10			) AS		DT_EMISSAO           
,	SUBSTRING(REPLACE(dados,';',''),	1050	,10			) AS		DT_PAGAMENTO         
,	SUBSTRING(REPLACE(dados,';',''),	1060	,9			) AS		VL_PAGO              
,	SUBSTRING(REPLACE(dados,';',''),	1069	,9			) AS		NR_CONTRATO          
,	SUBSTRING(REPLACE(dados,';',''),	1078	,1			) AS		DV_CONTRATO          
,	SUBSTRING(REPLACE(dados,';',''),	1079	,10			) AS		DT_FIM               
,	SUBSTRING(REPLACE(dados,';',''),	1089	,40			) AS		NM_CORRETOR          
,	SUBSTRING(REPLACE(dados,';',''),	1129	,11			) AS		CD_SUSEP             
,	SUBSTRING(REPLACE(dados,';',''),	1140	,9			) AS		CD_CPD               
,	SUBSTRING(REPLACE(dados,';',''),	1149	,7			) AS		CD_ANGARIADOR        
,	SUBSTRING(REPLACE(dados,';',''),	1156	,7			) AS		CD_AGENC_PROD        
,	SUBSTRING(REPLACE(dados,';',''),	1163	,3			) AS		NR_INSPETORIA        
,	SUBSTRING(REPLACE(dados,';',''),	1166	,2			) AS		CD_EVENTO            
,	SUBSTRING(REPLACE(dados,';',''),	1168	,10			) AS		DT_ULTIMO_EVENTO     
,	SUBSTRING(REPLACE(dados,';',''),	1178	,40			) AS		DS_ULTIMO_EVENTO     
,	SUBSTRING(REPLACE(dados,';',''),	1218	,10			) AS		DT_PRIMEIRO_EVENTO   
,	SUBSTRING(REPLACE(dados,';',''),	1228	,10			) AS		DT_ULTIMA_PENDENCIA  
,	SUBSTRING(REPLACE(dados,';',''),	1238	,70			) AS		DS_ULTIMA_PENDENCIA  
,	SUBSTRING(REPLACE(dados,';',''),	1308	,10			) AS		DT_ULTIMA_REJEICAO   
,	SUBSTRING(REPLACE(dados,';',''),	1318	,70			) AS		DS_ULTIMA_REJEICAO   
,	SUBSTRING(REPLACE(dados,';',''),	1388	,10			) AS		DT_NASCIMENTO        
,	SUBSTRING(REPLACE(dados,';',''),	1398	,1			) AS		ESTADO_CIVIL         
,	SUBSTRING(REPLACE(dados,';',''),	1399	,1			) AS		FILHOS               
,	SUBSTRING(REPLACE(dados,';',''),	1400	,1			) AS		FXETARIA_FILHOS      
,	SUBSTRING(REPLACE(dados,';',''),	1401	,1			) AS		IN_GARAGEM           
,	SUBSTRING(REPLACE(dados,';',''),	1402	,1			) AS		IN_OUTROS_VEICULOS   
,	SUBSTRING(REPLACE(dados,';',''),	1403	,1			) AS		SEXO                 
,	SUBSTRING(REPLACE(dados,';',''),	1404	,1			) AS		TIPO_PESSOA          
,	SUBSTRING(REPLACE(dados,';',''),	1405	,2			) AS		CD_SUPERVISOR01      
,	SUBSTRING(REPLACE(dados,';',''),	1407	,2			) AS		CD_SUPERVISOR02      
,	SUBSTRING(REPLACE(dados,';',''),	1409	,2			) AS		CD_SUPERVISOR03      
,	SUBSTRING(REPLACE(dados,';',''),	1411	,2			) AS		CD_SUPERVISOR04      
,	SUBSTRING(REPLACE(dados,';',''),	1413	,2			) AS		CD_SUPERVISOR05      
,	SUBSTRING(REPLACE(dados,';',''),	1415	,2			) AS		CD_SUPERVISOR06      
,	SUBSTRING(REPLACE(dados,';',''),	1417	,2			) AS		CD_SUPERVISOR07      
,	SUBSTRING(REPLACE(dados,';',''),	1419	,2			) AS		CD_SUPERVISOR08      
,	SUBSTRING(REPLACE(dados,';',''),	1421	,2			) AS		CD_SUPERVISOR09      
,	SUBSTRING(REPLACE(dados,';',''),	1423	,2			) AS		CD_SUPERVISOR10      
,	SUBSTRING(REPLACE(dados,';',''),	1425	,3			) AS		QT_TRANS_PROP        
,	SUBSTRING(REPLACE(dados,';',''),	1428	,4			) AS		CD_ALERTA01          
,	SUBSTRING(REPLACE(dados,';',''),	1432	,8			) AS		USER_LIBER01         
,	SUBSTRING(REPLACE(dados,';',''),	1440	,1			) AS		LIBRC_CONTR01        
,	SUBSTRING(REPLACE(dados,';',''),	1441	,10			) AS		DATA_LIBER01         
,	SUBSTRING(REPLACE(dados,';',''),	1451	,1			) AS		NIVEL_ALCADA01       
,	SUBSTRING(REPLACE(dados,';',''),	1452	,4			) AS		CD_ALERTA02          
,	SUBSTRING(REPLACE(dados,';',''),	1456	,8			) AS		USER_LIBER02         
,	SUBSTRING(REPLACE(dados,';',''),	1464	,1			) AS		LIBRC_CONTR02        
,	SUBSTRING(REPLACE(dados,';',''),	1465	,10			) AS		DATA_LIBER02         
,	SUBSTRING(REPLACE(dados,';',''),	1475	,1			) AS		NIVEL_ALCADA02       
,	SUBSTRING(REPLACE(dados,';',''),	1476	,4			) AS		CD_ALERTA03          
,	SUBSTRING(REPLACE(dados,';',''),	1480	,8			) AS		USER_LIBER03         
,	SUBSTRING(REPLACE(dados,';',''),	1488	,1			) AS		LIBRC_CONTR03        
,	SUBSTRING(REPLACE(dados,';',''),	1489	,10			) AS		DATA_LIBER03         
,	SUBSTRING(REPLACE(dados,';',''),	1499	,1			) AS		NIVEL_ALCADA03       
,	SUBSTRING(REPLACE(dados,';',''),	1500	,4			) AS		CD_ALERTA04          
,	SUBSTRING(REPLACE(dados,';',''),	1504	,8			) AS		USER_LIBER04         
,	SUBSTRING(REPLACE(dados,';',''),	1512	,1			) AS		LIBRC_CONTR04        
,	SUBSTRING(REPLACE(dados,';',''),	1513	,10			) AS		DATA_LIBER04         
,	SUBSTRING(REPLACE(dados,';',''),	1523	,1			) AS		NIVEL_ALCADA04       
,	SUBSTRING(REPLACE(dados,';',''),	1524	,4			) AS		CD_ALERTA05          
,	SUBSTRING(REPLACE(dados,';',''),	1528	,8			) AS		USER_LIBER05         
,	SUBSTRING(REPLACE(dados,';',''),	1536	,1			) AS		LIBRC_CONTR05        
,	SUBSTRING(REPLACE(dados,';',''),	1537	,10			) AS		DATA_LIBER05         
,	SUBSTRING(REPLACE(dados,';',''),	1547	,1			) AS		NIVEL_ALCADA05       
,	SUBSTRING(REPLACE(dados,';',''),	1548	,4			) AS		CD_ALERTA06          
,	SUBSTRING(REPLACE(dados,';',''),	1552	,8			) AS		USER_LIBER06         
,	SUBSTRING(REPLACE(dados,';',''),	1560	,1			) AS		LIBRC_CONTR06        
,	SUBSTRING(REPLACE(dados,';',''),	1561	,10			) AS		DATA_LIBER06         
,	SUBSTRING(REPLACE(dados,';',''),	1571	,1			) AS		NIVEL_ALCADA06       
,	SUBSTRING(REPLACE(dados,';',''),	1572	,4			) AS		CD_ALERTA07          
,	SUBSTRING(REPLACE(dados,';',''),	1576	,8			) AS		USER_LIBER07         
,	SUBSTRING(REPLACE(dados,';',''),	1584	,1			) AS		LIBRC_CONTR07        
,	SUBSTRING(REPLACE(dados,';',''),	1585	,10			) AS		DATA_LIBER07         
,	SUBSTRING(REPLACE(dados,';',''),	1595	,1			) AS		NIVEL_ALCADA07       
,	SUBSTRING(REPLACE(dados,';',''),	1596	,4			) AS		CD_ALERTA08          
,	SUBSTRING(REPLACE(dados,';',''),	1600	,8			) AS		USER_LIBER08         
,	SUBSTRING(REPLACE(dados,';',''),	1608	,1			) AS		LIBRC_CONTR08        
,	SUBSTRING(REPLACE(dados,';',''),	1609	,10			) AS		DATA_LIBER08         
,	SUBSTRING(REPLACE(dados,';',''),	1619	,1			) AS		NIVEL_ALCADA08       
,	SUBSTRING(REPLACE(dados,';',''),	1620	,4			) AS		CD_ALERTA09          
,	SUBSTRING(REPLACE(dados,';',''),	1624	,8			) AS		USER_LIBER09         
,	SUBSTRING(REPLACE(dados,';',''),	1632	,1			) AS		LIBRC_CONTR09        
,	SUBSTRING(REPLACE(dados,';',''),	1633	,10			) AS		DATA_LIBER09         
,	SUBSTRING(REPLACE(dados,';',''),	1643	,1			) AS		NIVEL_ALCADA09       
,	SUBSTRING(REPLACE(dados,';',''),	1644	,4			) AS		CD_ALERTA10          
,	SUBSTRING(REPLACE(dados,';',''),	1648	,8			) AS		USER_LIBER10         
,	SUBSTRING(REPLACE(dados,';',''),	1656	,1			) AS		LIBRC_CONTR10        
,	SUBSTRING(REPLACE(dados,';',''),	1657	,10			) AS		DATA_LIBER10         
,	SUBSTRING(REPLACE(dados,';',''),	1667	,1			) AS		NIVEL_ALCADA10       
,	SUBSTRING(REPLACE(dados,';',''),	1668	,4			) AS		CD_ALERTA11          
,	SUBSTRING(REPLACE(dados,';',''),	1672	,8			) AS		USER_LIBER11         
,	SUBSTRING(REPLACE(dados,';',''),	1680	,1			) AS		LIBRC_CONTR11        
,	SUBSTRING(REPLACE(dados,';',''),	1681	,10			) AS		DATA_LIBER11         
,	SUBSTRING(REPLACE(dados,';',''),	1691	,1			) AS		NIVEL_ALCADA11       
,	SUBSTRING(REPLACE(dados,';',''),	1692	,4			) AS		CD_ALERTA12          
,	SUBSTRING(REPLACE(dados,';',''),	1696	,8			) AS		USER_LIBER12         
,	SUBSTRING(REPLACE(dados,';',''),	1704	,1			) AS		LIBRC_CONTR12        
,	SUBSTRING(REPLACE(dados,';',''),	1705	,10			) AS		DATA_LIBER12         
,	SUBSTRING(REPLACE(dados,';',''),	1715	,1			) AS		NIVEL_ALCADA12       
,	SUBSTRING(REPLACE(dados,';',''),	1716	,4			) AS		CD_ALERTA13          
,	SUBSTRING(REPLACE(dados,';',''),	1720	,8			) AS		USER_LIBER13         
,	SUBSTRING(REPLACE(dados,';',''),	1728	,1			) AS		LIBRC_CONTR13        
,	SUBSTRING(REPLACE(dados,';',''),	1729	,10			) AS		DATA_LIBER13         
,	SUBSTRING(REPLACE(dados,';',''),	1739	,1			) AS		NIVEL_ALCADA13       
,	SUBSTRING(REPLACE(dados,';',''),	1740	,4			) AS		CD_ALERTA14          
,	SUBSTRING(REPLACE(dados,';',''),	1744	,8			) AS		USER_LIBER14         
,	SUBSTRING(REPLACE(dados,';',''),	1752	,1			) AS		LIBRC_CONTR14        
,	SUBSTRING(REPLACE(dados,';',''),	1753	,10			) AS		DATA_LIBER14         
,	SUBSTRING(REPLACE(dados,';',''),	1763	,1			) AS		NIVEL_ALCADA14       
,	SUBSTRING(REPLACE(dados,';',''),	1764	,4			) AS		CD_ALERTA15          
,	SUBSTRING(REPLACE(dados,';',''),	1768	,8			) AS		USER_LIBER15         
,	SUBSTRING(REPLACE(dados,';',''),	1776	,1			) AS		LIBRC_CONTR15        
,	SUBSTRING(REPLACE(dados,';',''),	1777	,10			) AS		DATA_LIBER15         
,	SUBSTRING(REPLACE(dados,';',''),	1787	,1			) AS		NIVEL_ALCADA15       
,	SUBSTRING(REPLACE(dados,';',''),	1788	,4			) AS		CD_ALERTA16          
,	SUBSTRING(REPLACE(dados,';',''),	1792	,8			) AS		USER_LIBER16         
,	SUBSTRING(REPLACE(dados,';',''),	1800	,1			) AS		LIBRC_CONTR16        
,	SUBSTRING(REPLACE(dados,';',''),	1801	,10			) AS		DATA_LIBER16         
,	SUBSTRING(REPLACE(dados,';',''),	1811	,1			) AS		NIVEL_ALCADA16       
,	SUBSTRING(REPLACE(dados,';',''),	1812	,4			) AS		CD_ALERTA17          
,	SUBSTRING(REPLACE(dados,';',''),	1816	,8			) AS		USER_LIBER17         
,	SUBSTRING(REPLACE(dados,';',''),	1824	,1			) AS		LIBRC_CONTR17        
,	SUBSTRING(REPLACE(dados,';',''),	1825	,10			) AS		DATA_LIBER17         
,	SUBSTRING(REPLACE(dados,';',''),	1835	,1			) AS		NIVEL_ALCADA17       
,	SUBSTRING(REPLACE(dados,';',''),	1836	,4			) AS		CD_ALERTA18          
,	SUBSTRING(REPLACE(dados,';',''),	1840	,8			) AS		USER_LIBER18         
,	SUBSTRING(REPLACE(dados,';',''),	1848	,1			) AS		LIBRC_CONTR18        
,	SUBSTRING(REPLACE(dados,';',''),	1849	,10			) AS		DATA_LIBER18         
,	SUBSTRING(REPLACE(dados,';',''),	1859	,1			) AS		NIVEL_ALCADA18       
,	SUBSTRING(REPLACE(dados,';',''),	1860	,4			) AS		CD_ALERTA19          
,	SUBSTRING(REPLACE(dados,';',''),	1864	,8			) AS		USER_LIBER19         
,	SUBSTRING(REPLACE(dados,';',''),	1872	,1			) AS		LIBRC_CONTR19        
,	SUBSTRING(REPLACE(dados,';',''),	1873	,10			) AS		DATA_LIBER19         
,	SUBSTRING(REPLACE(dados,';',''),	1883	,1			) AS		NIVEL_ALCADA19       
,	SUBSTRING(REPLACE(dados,';',''),	1884	,4			) AS		CD_ALERTA20          
,	SUBSTRING(REPLACE(dados,';',''),	1888	,8			) AS		USER_LIBER20         
,	SUBSTRING(REPLACE(dados,';',''),	1896	,1			) AS		LIBRC_CONTR20        
,	SUBSTRING(REPLACE(dados,';',''),	1897	,10			) AS		DATA_LIBER20         
,	SUBSTRING(REPLACE(dados,';',''),	1907	,1			) AS		NIVEL_ALCADA20       
,	SUBSTRING(REPLACE(dados,';',''),	1908	,1			) AS		IN_CCB               
,	SUBSTRING(REPLACE(dados,';',''),	1909	,1			) AS		IN_AVISTA            
,	SUBSTRING(REPLACE(dados,';',''),	1910	,3			) AS		CD_MOTIVO01          
,	SUBSTRING(REPLACE(dados,';',''),	1913	,50			) AS		DS_MOTIVO01          
,	SUBSTRING(REPLACE(dados,';',''),	1963	,3			) AS		CD_MOTIVO02          
,	SUBSTRING(REPLACE(dados,';',''),	1966	,50			) AS		DS_MOTIVO02          
,	SUBSTRING(REPLACE(dados,';',''),	2016	,3			) AS		CD_MOTIVO03          
,	SUBSTRING(REPLACE(dados,';',''),	2019	,50			) AS		DS_MOTIVO03          
,	SUBSTRING(REPLACE(dados,';',''),	2069	,3			) AS		CD_MOTIVO04          
,	SUBSTRING(REPLACE(dados,';',''),	2072	,50			) AS		DS_MOTIVO04          
,	SUBSTRING(REPLACE(dados,';',''),	2122	,3			) AS		CD_MOTIVO05          
,	SUBSTRING(REPLACE(dados,';',''),	2125	,50			) AS		DS_MOTIVO05          
,	SUBSTRING(REPLACE(dados,';',''),	2175	,3			) AS		CD_MOTIVO06          
,	SUBSTRING(REPLACE(dados,';',''),	2178	,50			) AS		DS_MOTIVO06          
,	SUBSTRING(REPLACE(dados,';',''),	2228	,3			) AS		CD_MOTIVO07          
,	SUBSTRING(REPLACE(dados,';',''),	2231	,50			) AS		DS_MOTIVO07          
,	SUBSTRING(REPLACE(dados,';',''),	2281	,3			) AS		CD_MOTIVO08          
,	SUBSTRING(REPLACE(dados,';',''),	2284	,50			) AS		DS_MOTIVO08          
,	SUBSTRING(REPLACE(dados,';',''),	2334	,3			) AS		CD_MOTIVO09          
,	SUBSTRING(REPLACE(dados,';',''),	2337	,50			) AS		DS_MOTIVO09          
,	SUBSTRING(REPLACE(dados,';',''),	2387	,3			) AS		CD_MOTIVO10          
,	SUBSTRING(REPLACE(dados,';',''),	2390	,50			) AS		DS_MOTIVO10          
,	SUBSTRING(REPLACE(dados,';',''),	2440	,2			) AS		CLASSE_BONUS         
,	SUBSTRING(REPLACE(dados,';',''),	2442	,1			) AS		CIND_SEGUR_RESID     
,	SUBSTRING(REPLACE(dados,';',''),	2443	,3			) AS		PDESC_ESPCL_CONCD    
,	SUBSTRING(REPLACE(dados,';',''),	2446	,3			) AS		CD_ANTI_FURTO        
,	SUBSTRING(REPLACE(dados,';',''),	2449	,30			) AS		DS_CARROCERIA        
,	SUBSTRING(REPLACE(dados,';',''),	2479	,3			) AS		CD_EQUIPAMENTO01     
,	SUBSTRING(REPLACE(dados,';',''),	2482	,3			) AS		CD_EQUIPAMENTO02     
,	SUBSTRING(REPLACE(dados,';',''),	2485	,3			) AS		CD_EQUIPAMENTO03     
,	SUBSTRING(REPLACE(dados,';',''),	2488	,3			) AS		CD_EQUIPAMENTO04     
,	SUBSTRING(REPLACE(dados,';',''),	2491	,3			) AS		CD_EQUIPAMENTO05     
,	SUBSTRING(REPLACE(dados,';',''),	2494	,3			) AS		CD_EQUIPAMENTO06     
,	SUBSTRING(REPLACE(dados,';',''),	2497	,3			) AS		CD_EQUIPAMENTO07     
,	SUBSTRING(REPLACE(dados,';',''),	2500	,3			) AS		CD_EQUIPAMENTO08     
,	SUBSTRING(REPLACE(dados,';',''),	2503	,3			) AS		CD_EQUIPAMENTO09     
,	SUBSTRING(REPLACE(dados,';',''),	2506	,3			) AS		CD_EQUIPAMENTO10     
,	SUBSTRING(REPLACE(dados,';',''),	2509	,2			) AS		CD_ACESSORIO01       
,	SUBSTRING(REPLACE(dados,';',''),	2511	,2			) AS		CD_ACESSORIO02       
,	SUBSTRING(REPLACE(dados,';',''),	2513	,2			) AS		CD_ACESSORIO03       
,	SUBSTRING(REPLACE(dados,';',''),	2515	,2			) AS		CD_ACESSORIO04       
,	SUBSTRING(REPLACE(dados,';',''),	2517	,2			) AS		CD_ACESSORIO05       
,	SUBSTRING(REPLACE(dados,';',''),	2519	,2			) AS		CD_ACESSORIO06       
,	SUBSTRING(REPLACE(dados,';',''),	2521	,2			) AS		CD_ACESSORIO07       
,	SUBSTRING(REPLACE(dados,';',''),	2523	,2			) AS		CD_ACESSORIO08       
,	SUBSTRING(REPLACE(dados,';',''),	2525	,2			) AS		CD_ACESSORIO09       
,	SUBSTRING(REPLACE(dados,';',''),	2527	,2			) AS		CD_ACESSORIO10       
,	SUBSTRING(REPLACE(dados,';',''),	2529	,10			) AS		DT_SAIDA_CONC        
,	SUBSTRING(REPLACE(dados,';',''),	2539	,1			) AS		IN_CHASSI_REM        
,	SUBSTRING(REPLACE(dados,';',''),	2540	,1			) AS		IN_VEIC_TRANSF       
,	SUBSTRING(REPLACE(dados,';',''),	2541	,1			) AS		IN_SUPER_AUTO        
,	SUBSTRING(REPLACE(dados,';',''),	2542	,2			) AS		CLASSE_BONUS_ANT     
,	SUBSTRING(REPLACE(dados,';',''),	2544	,2			) AS		NR_SINISTRO          
,	SUBSTRING(REPLACE(dados,';',''),	2546	,1			) AS		CD_PROCED_VEIC       
,	SUBSTRING(REPLACE(dados,';',''),	2547	,10			) AS		NR_PROPOSTA_ORIG     
,	SUBSTRING(REPLACE(dados,';',''),	2557	,10			) AS		DT_EFET_PROP_ORIG    
,	SUBSTRING(REPLACE(dados,';',''),	2567	,8			) AS		CD_USUARIO_SOL       
,	SUBSTRING(REPLACE(dados,';',''),	2575	,5			) AS		NR_ITENS_FROTA       
,	SUBSTRING(REPLACE(dados,';',''),	2580	,1			) AS		CIND_NOVA_TARIFA     
,	SUBSTRING(REPLACE(dados,';',''),	2581	,3			) AS		CD_REGIAO_TARIFARIA  
,	SUBSTRING(REPLACE(dados,';',''),	2584	,6			) AS		VERSAO_TARIFA        
,	SUBSTRING(REPLACE(dados,';',''),	2590	,6			) AS		NR_APOLICE           
,	SUBSTRING(REPLACE(dados,';',''),	2596	,8			) AS		VL_PREMIO_RCF_DM     
,	SUBSTRING(REPLACE(dados,';',''),	2604	,1			) AS		PREM_RCF_DM_SINAL    
,	SUBSTRING(REPLACE(dados,';',''),	2605	,8			) AS		VL_PREMIO_RCF_DC     
,	SUBSTRING(REPLACE(dados,';',''),	2613	,1			) AS		PREM_RCF_DC_SINAL    
,	SUBSTRING(REPLACE(dados,';',''),	2614	,8			) AS		VL_PREMIO_RCF_DMO    
,	SUBSTRING(REPLACE(dados,';',''),	2622	,1			) AS		PREM_RCF_DMO_SINAL   
,	SUBSTRING(REPLACE(dados,';',''),	2623	,8			) AS		VL_PREMIO_RCF_GU     
,	SUBSTRING(REPLACE(dados,';',''),	2631	,1			) AS		PREM_RCF_GU_SINAL    
,	SUBSTRING(REPLACE(dados,';',''),	2632	,8			) AS		VL_PREMIO_APP_MO     
,	SUBSTRING(REPLACE(dados,';',''),	2640	,1			) AS		PREM_APP_MO_SINAL    
,	SUBSTRING(REPLACE(dados,';',''),	2641	,8			) AS		VL_PREMIO_APP_INV    
,	SUBSTRING(REPLACE(dados,';',''),	2649	,1			) AS		PREM_APP_INV_SINAL   
,	SUBSTRING(REPLACE(dados,';',''),	2650	,2			) AS		TIPO_VEICULO         
,	SUBSTRING(REPLACE(dados,';',''),	2652	,8			) AS		VL_PREMIO_CASCO      
,	SUBSTRING(REPLACE(dados,';',''),	2660	,1			) AS		PREM_CASCO_SINAL     
,	SUBSTRING(REPLACE(dados,';',''),	2661	,8			) AS		VL_PREMIO_DESP_EXT   
,	SUBSTRING(REPLACE(dados,';',''),	2669	,1			) AS		PREM_DESP_EXT_SINAL  
,	SUBSTRING(REPLACE(dados,';',''),	2670	,8			) AS		VL_PREMIO_CARROCERIA 
,	SUBSTRING(REPLACE(dados,';',''),	2678	,1			) AS		PREM_CARROCER_SINAL  
,	SUBSTRING(REPLACE(dados,';',''),	2679	,8			) AS		VL_PREMIO_EQUIP      
,	SUBSTRING(REPLACE(dados,';',''),	2687	,1			) AS		PREM_EQUIP_SINAL     
,	SUBSTRING(REPLACE(dados,';',''),	2688	,8			) AS		VL_PREMIO_ACCESS     
,	SUBSTRING(REPLACE(dados,';',''),	2696	,1			) AS		PREM_ACESS_SINAL     
,	SUBSTRING(REPLACE(dados,';',''),	2697	,8			) AS		VL_PREMIO_DIARIAS    
,	SUBSTRING(REPLACE(dados,';',''),	2705	,1			) AS		PREM_DIARIAS_SINAL   
,	SUBSTRING(REPLACE(dados,';',''),	2706	,8			) AS		VL_PREMIO_KIT_GAS    
,	SUBSTRING(REPLACE(dados,';',''),	2714	,1			) AS		PREM_KIT_GAS_SINAL   
,	SUBSTRING(REPLACE(dados,';',''),	2715	,8			) AS		VL_SERVICO_DIA_NOITE 
,	SUBSTRING(REPLACE(dados,';',''),	2723	,1			) AS		SERV_DIA_NOITE_SINAL 
,	SUBSTRING(REPLACE(dados,';',''),	2724	,8			) AS		VL_SERVICO_CARRO_RES 
,	SUBSTRING(REPLACE(dados,';',''),	2732	,1			) AS		SERV_CARRO_RES_SINAL 
,	SUBSTRING(REPLACE(dados,';',''),	2733	,8			) AS		VL_SERVICO_VIDROS    
,	SUBSTRING(REPLACE(dados,';',''),	2741	,1			) AS		SERV_VIDROS_SINAL    
,	SUBSTRING(REPLACE(dados,';',''),	2742	,3			) AS		TIPO_CLIENTE         
,	SUBSTRING(REPLACE(dados,';',''),	2745	,2			) AS		CD_FRANQUIA          
,	SUBSTRING(REPLACE(dados,';',''),	2747	,1			) AS		FLG_RENOVA_PROPRIA   
,	SUBSTRING(REPLACE(dados,';',''),	2748	,2			) AS		CD_RELACAO_SEG_PROP  
,	SUBSTRING(REPLACE(dados,';',''),	2750	,1			) AS		TP_CANCELAMENTO      
,	SUBSTRING(REPLACE(dados,';',''),	2751	,1			) AS		IN_COMODATO          
,	SUBSTRING(REPLACE(dados,';',''),	2752	,3			) AS		CD_SEMI_REBOQUE      
,	SUBSTRING(REPLACE(dados,';',''),	2755	,9			) AS		VL_LMI_BLINDAGEM     
,	SUBSTRING(REPLACE(dados,';',''),	2764	,8			) AS		VL_PREMIO_BLINDAGEM  
,	SUBSTRING(REPLACE(dados,';',''),	2772	,1			) AS		PREM_BLINDAGEM_SINAL 
,	SUBSTRING(REPLACE(dados,';',''),	2773	,9			) AS		VL_LMI_KITGAS        
,	SUBSTRING(REPLACE(dados,';',''),	2782	,8			) AS		VL_FRANQUIA_CASCO    
,	SUBSTRING(REPLACE(dados,';',''),	2790	,8			) AS		VL_FRANQUIA_KITGAS   
,	SUBSTRING(REPLACE(dados,';',''),	2798	,3			) AS		PDESC_CRIVO          
,	SUBSTRING(REPLACE(dados,';',''),	2801	,8			) AS		NOPER_CRIVO          
,	SUBSTRING(REPLACE(dados,';',''),	2809	,7			) AS		CRETOR_CRIVO         
,	SUBSTRING(REPLACE(dados,';',''),	2816	,1			) AS		CIND_RCUSA_COTAC     
,	SUBSTRING(REPLACE(dados,';',''),	2817	,1			) AS		CIND_SBCAO_CRIVO     
,	SUBSTRING(REPLACE(dados,';',''),	2818	,3			) AS		PDESC_LIM_CRIVO      
,	SUBSTRING(REPLACE(dados,';',''),	2821	,4			) AS		QPTO_OPER_CRIVO      
,	SUBSTRING(REPLACE(dados,';',''),	2825	,12			) AS		CCLASF_SERASA_OPER   
,	SUBSTRING(REPLACE(dados,';',''),	2837	,1			) AS		COBR_VIA_CCBS        
,	SUBSTRING(REPLACE(dados,';',''),	2838	,1			) AS		CIND_LIBER_CCB       
,	SUBSTRING(REPLACE(dados,';',''),	2839	,2			) AS		CD_USO_VEIC          
,	SUBSTRING(REPLACE(dados,';',''),	2841	,2			) AS		CD_COMBUST           
,	SUBSTRING(REPLACE(dados,';',''),	2843	,1			) AS		CCONTX_OPER_CRIVO    
,	SUBSTRING(REPLACE(dados,';',''),	2844	,3			) AS		PC_COMISS_AUTO       
,	SUBSTRING(REPLACE(dados,';',''),	2847	,3			) AS		PC_COMISS_RCF        
,	SUBSTRING(REPLACE(dados,';',''),	2850	,3			) AS		PC_COMISS_APP        
,	SUBSTRING(REPLACE(dados,';',''),	2853	,1			) AS		IN_REVENDA           
,	SUBSTRING(REPLACE(dados,';',''),	2854	,6			) AS		CGRP_REVDA_VEIC      
,	SUBSTRING(REPLACE(dados,';',''),	2860	,26			) AS		DINIC_VGCIA_GRP      
,	SUBSTRING(REPLACE(dados,';',''),	2886	,4			) AS		CSEQ_REVDA_VEIC      
,	SUBSTRING(REPLACE(dados,';',''),	2890	,1			) AS		IN_CARTAO            
,	SUBSTRING(REPLACE(dados,';',''),	2891	,18			) AS		NR_CARTAO_CREDITO    
,	SUBSTRING(REPLACE(dados,';',''),	2909	,3			) AS		COPER_CATAO          
,	SUBSTRING(REPLACE(dados,';',''),	2912	,6			) AS		CVALDD_CATAO_CREDT   
,	SUBSTRING(REPLACE(dados,';',''),	2918	,30			) AS		APLICATIVO           
,	SUBSTRING(REPLACE(dados,';',''),	2948	,15			) AS		CCNPJ_CRRTR          
,	SUBSTRING(REPLACE(dados,';',''),	2963	,10			) AS		CNRO_LOTE_FROTA      
,	SUBSTRING(REPLACE(dados,';',''),	2973	,14			) AS		CODIGO_CI            
,	SUBSTRING(REPLACE(dados,';',''),	2987	,1			) AS		CSEXO_PPRIE_VEIC     
,	SUBSTRING(REPLACE(dados,';',''),	2988	,10			) AS		DNASC_PPRIE_VEIC     
,	SUBSTRING(REPLACE(dados,';',''),	2998	,1			) AS		CEST_CVIL_PPRIE      
,	SUBSTRING(REPLACE(dados,';',''),	2999	,11			) AS		CCONTR_ESPCL         
,	SUBSTRING(REPLACE(dados,';',''),	3010	,1			) AS		CIND_MESA_NEGOC      
,	SUBSTRING(REPLACE(dados,';',''),	3011	,10			) AS		PROPOSTA_ANT         
,	SUBSTRING(REPLACE(dados,';',''),	3021	,2			) AS		CTPO_FUNC_PBLIC      
,	SUBSTRING(REPLACE(dados,';',''),	3023	,1			) AS		CIND_LIBR_MOTVO      
,	SUBSTRING(REPLACE(dados,';',''),	3024	,1			) AS		CIND_ACEIT_RESTR     
,	SUBSTRING(REPLACE(dados,';',''),	3025	,1			) AS		CIND_SEGURO_CORRETOR 
,	SUBSTRING(REPLACE(dados,';',''),	3026	,3			) AS		COPCAO_SEGUR_RESID   
,	SUBSTRING(REPLACE(dados,';',''),	3029	,3			) AS		COD_PRESTADORA       
,	SUBSTRING(REPLACE(dados,';',''),	3032	,1			) AS		IN_PPV               
,	SUBSTRING(REPLACE(dados,';',''),	3033	,1			) AS		TIPO_CONTA           
,	SUBSTRING(REPLACE(dados,';',''),	3034	,4			) AS		BANCO_CRED           
,	SUBSTRING(REPLACE(dados,';',''),	3038	,5			) AS		AGENCIA_CRED         
,	SUBSTRING(REPLACE(dados,';',''),	3043	,15			) AS		NR_CONTA_CRED        
,	SUBSTRING(REPLACE(dados,';',''),	3058	,2			) AS		DV_CONTA_CRED        
,	SUBSTRING(REPLACE(dados,';',''),	3060	,5			) AS		VFATOR_AGRVO_LNEAR   
,	SUBSTRING(REPLACE(dados,';',''),	3065	,14			) AS		CD_SUSEP14           
,	SUBSTRING(REPLACE(dados,';',''),	3079	,8			) AS		USUARIO_COTACAO      
,	SUBSTRING(REPLACE(dados,';',''),	3087	,15			) AS		CPF_CNPJ_COTACAO     
,	SUBSTRING(REPLACE(dados,';',''),	3102	,1			) AS		PESSOA_COTACAO       
,	SUBSTRING(REPLACE(dados,';',''),	3103	,64			) AS		EMAIL_SEGURADO       
,	SUBSTRING(REPLACE(dados,';',''),	3167	,11			) AS		TP_UTIL_FONE_RES     
,	SUBSTRING(REPLACE(dados,';',''),	3178	,3			) AS		NR_DDD_RES           
,	SUBSTRING(REPLACE(dados,';',''),	3181	,11			) AS		NR_FONE_RES          
,	SUBSTRING(REPLACE(dados,';',''),	3192	,11			) AS		TP_UTIL_FONE_COM     
,	SUBSTRING(REPLACE(dados,';',''),	3203	,3			) AS		NR_DDD_COM           
,	SUBSTRING(REPLACE(dados,';',''),	3206	,11			) AS		NR_FONE_COM          
,	SUBSTRING(REPLACE(dados,';',''),	3217	,11			) AS		TP_UTIL_FONE_CEL     
,	SUBSTRING(REPLACE(dados,';',''),	3228	,3			) AS		NR_DDD_CEL           
,	SUBSTRING(REPLACE(dados,';',''),	3231	,11			) AS		NR_FONE_CEL          
,	SUBSTRING(REPLACE(dados,';',''),	3242	,11			) AS		TP_UTIL_FONE_CONL    
,	SUBSTRING(REPLACE(dados,';',''),	3253	,3			) AS		NR_DDD_CON           
,	SUBSTRING(REPLACE(dados,';',''),	3256	,11			) AS		NR_FONE_CON          
,	SUBSTRING(REPLACE(dados,';',''),	3267	,20			) AS		NM_FONE_CON          
,	SUBSTRING(REPLACE(dados,';',''),	3287	,3			) AS		DESC_DCE             
,	SUBSTRING(REPLACE(dados,';',''),	3290	,7			) AS		CNEGOC_DCE           
,	SUBSTRING(REPLACE(dados,';',''),	3297	,1			) AS		CTPO_CEN_DEC         
,	SUBSTRING(REPLACE(dados,';',''),	3298	,7			) AS		PREM_LIQ_RESID       
,	SUBSTRING(REPLACE(dados,';',''),	3305	,1			) AS		CTPO_PRFIL_PROPN     
,	SUBSTRING(REPLACE(dados,';',''),	3306	,1			) AS		CIND_PPRIE_VEIC      
,	SUBSTRING(REPLACE(dados,';',''),	3307	,1			) AS		CIND_CNDOR_PRINC     
,	SUBSTRING(REPLACE(dados,';',''),	3308	,55			) AS		ICNDOR               
,	SUBSTRING(REPLACE(dados,';',''),	3363	,11			) AS		CCPF_PSSOA_CNDOR     
,	SUBSTRING(REPLACE(dados,';',''),	3374	,10			) AS		DNASC_CNDOR          
,	SUBSTRING(REPLACE(dados,';',''),	3384	,1			) AS		CSEXO_CNDOR          
,	SUBSTRING(REPLACE(dados,';',''),	3385	,1			) AS		CEST_CVIL_CNDOR      
,	SUBSTRING(REPLACE(dados,';',''),	3386	,2			) AS		CTPO_OUTRO_CNDOR     
,	SUBSTRING(REPLACE(dados,';',''),	3388	,1			) AS		CTPO_GARAG_PNOIT     
,	SUBSTRING(REPLACE(dados,';',''),	3389	,2			) AS		CATVDD_PRINC_CNDOR   
,	SUBSTRING(REPLACE(dados,';',''),	3391	,2			) AS		CRAMO_ATV_PRINC_CNDOR
,	SUBSTRING(REPLACE(dados,';',''),	3393	,1			) AS		CUTILZ_VEIC_TRAB     
,	SUBSTRING(REPLACE(dados,';',''),	3394	,1			) AS		CLOC_FIXO_TRAB       
,	SUBSTRING(REPLACE(dados,';',''),	3395	,8			) AS		NCEP_LOC_TRAB        
,	SUBSTRING(REPLACE(dados,';',''),	3403	,1			) AS		CTPO_GARAG_LOC_TRAB  
,	SUBSTRING(REPLACE(dados,';',''),	3404	,1			) AS		CUTILZ_VEIC_STUDO    
,	SUBSTRING(REPLACE(dados,';',''),	3405	,1			) AS		CLOC_FIXO_STUDO      
,	SUBSTRING(REPLACE(dados,';',''),	3406	,8			) AS		NCEP_LOC_STUDO       
,	SUBSTRING(REPLACE(dados,';',''),	3414	,1			) AS		CTPO_GARAG_LOC_STUDO 
,	SUBSTRING(REPLACE(dados,';',''),	3415	,1			) AS		CFAIXA_KM            
,	SUBSTRING(REPLACE(dados,';',''),	3416	,9			) AS		VL_PREMIO_RCF        
,	SUBSTRING(REPLACE(dados,';',''),	3425	,1			) AS		PREM_RCF_SINAL       
,	SUBSTRING(REPLACE(dados,';',''),	3426	,9			) AS		VL_PREMIO_APP        
,	SUBSTRING(REPLACE(dados,';',''),	3435	,1			) AS		PREM_APP_SINAL       
,	SUBSTRING(REPLACE(dados,';',''),	3436	,10			) AS		CD_VEICULO_NOVO      
,	SUBSTRING(REPLACE(dados,';',''),	3446	,10			) AS		CD_MOLICAR           
,	SUBSTRING(REPLACE(dados,';',''),	3456	,1			) AS		IN_ELETRO_HIDRAULICA 
,	SUBSTRING(REPLACE(dados,';',''),	3457	,1			) AS		IN_ELETRICA          
,	SUBSTRING(REPLACE(dados,';',''),	3458	,1			) AS		IN_OPC_OUTROS        
,	SUBSTRING(REPLACE(dados,';',''),	3459	,1			) AS		CIND_CATAO_BDSCO     
,	SUBSTRING(REPLACE(dados,';',''),	3460	,6			) AS		NR_ENDOSSO           
,	SUBSTRING(REPLACE(dados,';',''),	3466	,9			) AS		VL_PREM_TAR_CASCO    
,	SUBSTRING(REPLACE(dados,';',''),	3475	,9			) AS		VL_PREM_TAR_ACESS    
,	SUBSTRING(REPLACE(dados,';',''),	3484	,9			) AS		VL_PREM_TAR_CARROC   
,	SUBSTRING(REPLACE(dados,';',''),	3493	,9			) AS		VL_PREM_TAR_EQUIP    
,	SUBSTRING(REPLACE(dados,';',''),	3502	,9			) AS		VL_PREM_TAR_BLIND    
,	SUBSTRING(REPLACE(dados,';',''),	3511	,9			) AS		VL_PREM_TAR_CARRO_RES
,	SUBSTRING(REPLACE(dados,';',''),	3520	,9			) AS		VL_PREM_TAR_DESP_EXT 
,	SUBSTRING(REPLACE(dados,';',''),	3529	,9			) AS		VL_PREM_TAR_KITGAS   
,	SUBSTRING(REPLACE(dados,';',''),	3538	,9			) AS		VL_PREM_TAR_DIARIAS  
,	SUBSTRING(REPLACE(dados,';',''),	3547	,9			) AS		VL_PREM_TAR_ADN      
,	SUBSTRING(REPLACE(dados,';',''),	3556	,9			) AS		VL_PREM_TAR_VIDROS   
,	SUBSTRING(REPLACE(dados,';',''),	3565	,9			) AS		VL_PREM_TAR_AUTO     
,	SUBSTRING(REPLACE(dados,';',''),	3574	,9			) AS		VL_PREM_TAR_DM       
,	SUBSTRING(REPLACE(dados,';',''),	3583	,9			) AS		VL_PREM_TAR_DC       
,	SUBSTRING(REPLACE(dados,';',''),	3592	,9			) AS		VL_PREM_TAR_DMO      
,	SUBSTRING(REPLACE(dados,';',''),	3601	,9			) AS		VL_PREM_TAR_GU       
,	SUBSTRING(REPLACE(dados,';',''),	3610	,9			) AS		VL_PREM_TAR_RCF      
,	SUBSTRING(REPLACE(dados,';',''),	3619	,9			) AS		VL_PREM_TAR_MORTE    
,	SUBSTRING(REPLACE(dados,';',''),	3628	,9			) AS		VL_PREM_TAR_INVAL    
,	SUBSTRING(REPLACE(dados,';',''),	3637	,9			) AS		VL_PREM_TAR_APP      
,	SUBSTRING(REPLACE(dados,';',''),	3646	,9			) AS		VL_PREM_TAR_TOTAL    
,	SUBSTRING(REPLACE(dados,';',''),	3655	,10			) AS		DT_CONCIL_VP         
,	SUBSTRING(REPLACE(dados,';',''),	3665	,10			) AS		DT_TRANSM_VP         
,	SUBSTRING(REPLACE(dados,';',''),	3675	,9			) AS		NR_VISTORIA          
,	SUBSTRING(REPLACE(dados,';',''),	3684	,20			) AS		CD_SITUACAO_VP       
,	SUBSTRING(REPLACE(dados,';',''),	3704	,4			) AS		CD_EMPR_VIST         
,	SUBSTRING(REPLACE(dados,';',''),	3708	,1			) AS		IND_VP_GERADA_CALC   
,	SUBSTRING(REPLACE(dados,';',''),	3709	,32			) AS		IND_VP_REALIZ        
,	SUBSTRING(REPLACE(dados,';',''),	3741	,5			) AS		CD_OCUP_PRINC        
,	SUBSTRING(REPLACE(dados,';',''),	3746	,3			) AS		IND_CERTF_DIGITAL    
,	SUBSTRING(REPLACE(dados,';',''),	3749	,9			) AS		VL_PREMIO_DCE        
,	SUBSTRING(REPLACE(dados,';',''),	3758	,9			) AS		VL_DESC_DCE          
,	SUBSTRING(REPLACE(dados,';',''),	3767	,9			) AS		VL_PREMIO_CAPIT_RES  
,	SUBSTRING(REPLACE(dados,';',''),	3776	,9			) AS		VL_PREMIO_ADN_RES    
,	SUBSTRING(REPLACE(dados,';',''),	3785	,5			) AS		NR_LOGRAD            
,	SUBSTRING(REPLACE(dados,';',''),	3790	,5			) AS		NR_LOGRAD_RISCO      
,	SUBSTRING(REPLACE(dados,';',''),	3795	,2			) AS		CMOD_TRFIO           
,	SUBSTRING(REPLACE(dados,';',''),	3797	,5			) AS		CNOVA_RGIAO_RISCO    
,	SUBSTRING(REPLACE(dados,';',''),	3802	,6			) AS		VPRMIO_PERDA_PCIAL   
,	SUBSTRING(REPLACE(dados,';',''),	3808	,6			) AS		VPRMIO_PERDA_TOT     
,	SUBSTRING(REPLACE(dados,';',''),	3814	,6			) AS		VPRMIO_ROUBO_FURTO   
,	SUBSTRING(REPLACE(dados,';',''),	3820	,6			) AS		VSERVC_ADN           
,	SUBSTRING(REPLACE(dados,';',''),	3826	,6			) AS		VSERVC_VIDRO         
,	SUBSTRING(REPLACE(dados,';',''),	3832	,6			) AS		VSERVC_CAR_RES       
,	SUBSTRING(REPLACE(dados,';',''),	3838	,6			) AS		CCLASS_BONUS_PP      
,	SUBSTRING(REPLACE(dados,';',''),	3844	,6			) AS		CCLASS_BONUS_PT      
,	SUBSTRING(REPLACE(dados,';',''),	3850	,6			) AS		CCLASS_BONUS_RF      
,	SUBSTRING(REPLACE(dados,';',''),	3856	,6			) AS		CCLASS_BONUS_DM      
,	SUBSTRING(REPLACE(dados,';',''),	3862	,2			) AS		CSIT_CCB             
,	SUBSTRING(REPLACE(dados,';',''),	3864	,128			) AS		FILLER   
from LarguraFixaNasa