SET DATEFORMAT dmy

SELECT 
	CASE WHEN MODALIDADE = 'E' THEN 'ENDOSSO'
		 WHEN MODALIDADE = 'N' THEN 'SEGURO NOVO'
	     WHEN MODALIDADE = 'R' THEN 'RENOVACAO' END AS MODALIDADE	   
	,CAST(CD_CIA AS INT) AS CD_CIA
	,NM_CIA
	,CAST(CD_SUCURSAL AS INT) AS CD_SUCURSAL
	,CAST(NR_PROPOSTA AS BIGINT) AS NR_PROPOSTA
	,CAST(NR_ITEM AS INT) AS NR_ITEM      
	,CASE WHEN TP_SISTEMA = 'I' THEN 'INDIVIDUAL'
		  WHEN TP_SISTEMA = 'T' THEN 'TELEEMPRESA'
		  WHEN TP_SISTEMA = 'F' THEN 'FROTA' END AS TP_SISTEMA      	   
	,CASE WHEN CD_ORIGEM = 1 THEN 'MATRIZ'
		  WHEN CD_ORIGEM = 2 THEN 'SUCURSAL'
		  WHEN CD_ORIGEM = 3 THEN 'AGENCIA'
		  WHEN CD_ORIGEM = 4 THEN 'CORRETOR ESPECIAL'
		  WHEN CD_ORIGEM = 5 THEN 'CORRETOR SEGUROS'
		  WHEN CD_ORIGEM = 6 THEN 'CALL CENTER'
		  WHEN CD_ORIGEM = 7 THEN 'INTRANET'
		  WHEN CD_ORIGEM = 8 THEN 'WEB'
		  WHEN CD_ORIGEM = 9 THEN 'ROTINA BATCH' END AS CD_ORIGEM 	   	   	         
	,CAST(CD_USUARIO AS INT) AS CD_USUARIO
	,CAST(CD_CIA_RENOVA AS INT) AS CD_CIA_RENOVA
	,CAST(CD_SUCURSAL_RENOVA AS INT) AS CD_SUCURSAL_RENOVA
	,CAST(NR_APOLICE_RENOVA AS BIGINT) AS NR_APOLICE_RENOVA
	,CAST(NR_ITEM_RENOVA AS INT) AS NR_ITEM_RENOVA
	,CAST(CD_EMPRESA AS INT) AS CD_EMPRESA
	,CAST(CD_DEPTO AS INT) AS CD_DEPTO
	,CAST(NR_MATRICULA AS BIGINT) AS NR_MATRICULA
	,CASE WHEN DS_PARENTESCO LIKE '*********%' THEN NULL ELSE DS_PARENTESCO END AS DS_PARENTESCO
	,NM_SEGURADO
	,DS_PESSOA
	,NM_ENDERECO
	,NM_BAIRRO
	,NM_MUNICIPIO
	,CD_ESTADO
	,CAST(NR_CEP AS BIGINT) AS NR_CEP
	,FILLER_VAGO
	,CAST(NR_CPF_CGC AS BIGINT) AS NR_CPF_CGC
	,NM_POR_CONTA_DE
	,dbo.fn_TrataData(DT_INICIO_VIGENCIA) AS DT_INICIO_VIGENCIA
	,dbo.fn_TrataData(DT_FINAL_VIGENCIA) AS DT_FINAL_VIGENCIA
	,NM_ENDERECO_RISCO
	,NM_COMPLEMENTO_RISCO
	,NM_BAIRRO_RISCO
	,NM_MUNICIPIO_RISCO
	,CD_ESTADO_RISCO
	,CAST(NR_CEP_RISCO AS INT) AS NR_CEP_RISCO
	-------------------------------------------------
	,CAST(CD_VEICULO AS INT) AS CD_VEICULO
	,DS_VEICULO
	,DS_FABRICANTE
	,NR_PLACA
	,NR_CHASSI
	,CAST(NR_ANO_FABRICACAO AS INT) AS NR_ANO_FABRICACAO
	,CAST(NR_ANO_MODELO AS INT) AS NR_ANO_MODELO
	,DS_COMBUSTIVEL
	,CAST(NR_PORTAS AS INT) AS NR_PORTAS
	,CAST(NR_EIXOS AS INT) AS NR_EIXOS
	,DS_USO_VEICULO
	,CAST(CD_REGIAO_FENASEG AS INT) AS CD_REGIAO_FENASEG
	,IN_SEM_OPCIONAIS
	,IN_AR
	,IN_DIRECAO
	,IN_CAMBIO_AUTOMATICO
	,IN_BANCO_COURO
	,IN_FREIO_ABS
	,IN_AIR_BAG
	,IN_CAMBIO_SEMI
	,IN_COMPREENSIVA
	,IN_INCENDIO_ROUBO
	,IN_RCF
	,IN_APP
	,IN_CARRO_RESERVA
	,IN_DIA_NOITE
	,IN_VIDRO
	,CAST(CD_CATEGORIA_AUTO AS INT) AS CD_CATEGORIA_AUTO
	,CAST(CD_CATEGORIA_RCF AS INT) AS CD_CATEGORIA_RCF
	,IN_BONUS
	,CAST(FT_AJUSTE_VMR AS INT) AS FT_AJUSTE_VMR
	,dbo.fn_TrataMoney(VL_IS_CASCO) AS VL_IS_CASCO -- FUNCTION      
	,dbo.fn_TrataMoney(VL_DESP_EXTR) AS VL_DESP_EXTR
	,dbo.fn_TrataMoney(VL_IS_CARROCERIA) AS VL_IS_CARROCERIA
	,dbo.fn_TrataMoney(VL_IS_EQUIPAMENTO) AS VL_IS_EQUIPAMENTO
	,dbo.fn_TrataMoney(VL_IS_ACESSORIO) AS VL_IS_ACESSORIO
	,dbo.fn_TrataMoney(VL_DIARIA_PARALIZ) AS VL_DIARIA_PARALIZ
	,CAST(CD_FIPE AS INT) AS CD_FIPE
	,dbo.fn_TrataMoney(VL_IS_DM) AS VL_IS_DM
	,dbo.fn_TrataMoney(VL_IS_DP) AS VL_IS_DP
	,dbo.fn_TrataMoney(VL_IS_DMO) AS VL_IS_DMO
	,dbo.fn_TrataMoney(VL_IS_GU) AS VL_IS_GU
	,dbo.fn_TrataMoney(VL_IS_MORTE) AS VL_IS_MORTE
	,dbo.fn_TrataMoney(VL_IS_INVALIDEZ) AS VL_IS_INVALIDEZ
	,CAST(NR_PASSAGEIROS AS INT) AS NR_PASSAGEIROS
	------------------------------------------------
	
	,dbo.fn_TrataMoney(VL_PREMIO_AUTO) AS VL_PREMIO_AUTO
	,dbo.fn_TrataMoney(VL_FRANQUIA_VIDRO) AS VL_FRANQUIA_VIDRO
	,dbo.fn_TrataMoney(VL_FRANQUIA_CARROC) AS VL_FRANQUIA_CARROC
	,dbo.fn_TrataMoney(VL_FRANQUIA_EQUIP) AS VL_FRANQUIA_EQUIP
	,dbo.fn_TrataMoney(VL_PREMIO_LIQUIDO) AS VL_PREMIO_LIQUIDO
	,dbo.fn_TrataMoney(VL_CUSTO) AS VL_CUSTO
	,dbo.fn_TrataMoney(VL_ADICIONAL_FRAC) AS VL_ADICIONAL_FRAC
	,dbo.fn_TrataMoney(VL_IOF) AS VL_IOF
	,dbo.fn_TrataMoney(VL_PREMIO_TOTAL) AS VL_PREMIO_TOTAL
	,CAST(PC_TAXA_JUROS AS INT) AS PC_TAXA_JUROS
	,dbo.fn_TrataMoney(VL_1A_PRESTACAO) AS VL_A_PRESTACAO
	,CAST(QT_PRESTACAO_RESTANTE AS INT) AS QT_PRESTACAO_RESTANTE
	,dbo.fn_TrataMoney(VL_DEMAIS_PREST) AS VL_DEMAIS_PREST
	,CAST( NR_CLAUSULA01 AS INT) AS NR_CLAUSULA01
	,CAST( NR_CLAUSULA02 AS INT) AS NR_CLAUSULA02
	,CAST( NR_CLAUSULA03 AS INT) AS NR_CLAUSULA03
	,CAST( NR_CLAUSULA04 AS INT) AS NR_CLAUSULA04
	,CAST( NR_CLAUSULA05 AS INT) AS NR_CLAUSULA05
	,CAST( NR_CLAUSULA06 AS INT) AS NR_CLAUSULA06
	,CAST( NR_CLAUSULA07 AS INT) AS NR_CLAUSULA07
	,CAST( NR_CLAUSULA08 AS INT) AS NR_CLAUSULA08
	,CAST( NR_CLAUSULA09 AS INT) AS NR_CLAUSULA09
	,CAST( NR_CLAUSULA10 AS INT) AS NR_CLAUSULA10
	,CAST( NR_CLAUSULA11 AS INT) AS NR_CLAUSULA11
	,CAST( NR_CLAUSULA12 AS INT) AS NR_CLAUSULA12
	,CAST( NR_CLAUSULA13 AS INT) AS NR_CLAUSULA13
	,CAST( NR_CLAUSULA14 AS INT) AS NR_CLAUSULA14
	,CAST( NR_CLAUSULA15 AS INT) AS NR_CLAUSULA15
	,CAST( NR_CLAUSULA16 AS INT) AS NR_CLAUSULA16
	,CAST( NR_CLAUSULA17 AS INT) AS NR_CLAUSULA17
	,CAST( NR_CLAUSULA18 AS INT) AS NR_CLAUSULA18
	,CAST( NR_CLAUSULA19 AS INT) AS NR_CLAUSULA19
	,CAST( NR_CLAUSULA20 AS INT) AS NR_CLAUSULA20
	,CAST( NR_CLAUSULA21 AS INT) AS NR_CLAUSULA21
	,CAST( NR_CLAUSULA22 AS INT) AS NR_CLAUSULA22
	,CAST( NR_CLAUSULA23 AS INT) AS NR_CLAUSULA23
	,CAST( NR_CLAUSULA24 AS INT) AS NR_CLAUSULA24
	,CAST( NR_CLAUSULA25 AS INT) AS NR_CLAUSULA25
	,CAST( NR_CLAUSULA26 AS INT) AS NR_CLAUSULA26
	,CAST( NR_CLAUSULA27 AS INT) AS NR_CLAUSULA27
	,CAST( NR_CLAUSULA28 AS INT) AS NR_CLAUSULA28
	,CAST( NR_CLAUSULA29 AS INT) AS NR_CLAUSULA29
	,CAST( NR_CLAUSULA30 AS INT) AS NR_CLAUSULA30
	,CAST( NR_CLAUSULA31 AS INT) AS NR_CLAUSULA31
	,CAST( NR_CLAUSULA32 AS INT) AS NR_CLAUSULA32
	,CAST( NR_CLAUSULA33 AS INT) AS NR_CLAUSULA33
	,CAST( NR_CLAUSULA34 AS INT) AS NR_CLAUSULA34
	,CAST( NR_CLAUSULA35 AS INT) AS NR_CLAUSULA35
	,CAST( NR_CLAUSULA36 AS INT) AS NR_CLAUSULA36
	,CAST( NR_CLAUSULA37 AS INT) AS NR_CLAUSULA37
	,CAST( NR_CLAUSULA38 AS INT) AS NR_CLAUSULA38
	,CAST( NR_CLAUSULA39 AS INT) AS NR_CLAUSULA39
	,CAST( NR_CLAUSULA40 AS INT) AS NR_CLAUSULA40
	,IN_CARNE
	,IN_DEBITO
	,CAST(NR_BANCO AS INT) AS NR_BANCO
	,NR_AGENCIA      
	,NR_CONTA
	,CAST(PC_DESC_AUTO AS INT) AS PC_DESC_AUTO
	,CAST(PC_DESC_RCF AS INT) AS PC_DESC_RCF
	,CAST(PC_DESC_APP AS INT) AS PC_DESC_APP
	,CAST(NR_CCB AS BIGINT) AS NR_CCB
	,dbo.fn_TrataData(DT_EMISSAO) AS DT_EMISSAO
	,dbo.fn_TrataData(DT_PAGAMENTO) AS DT_PAGAMENTO
	,dbo.fn_TrataMoney(VL_PAGO) AS VL_PAGO
	,CAST(NR_CONTRATO AS INT) AS NR_CONTRATO
	,DV_CONTRATO
	,dbo.fn_TrataData(DT_FIM) AS DT_FIM
	-- ############################################
	--	CONTINUAR DAQUI .....
	-- ############################################
	,NM_CORRETOR
	,CAST(CD_SUSEP AS BIGINT) AS CD_SUSEP 
	,CAST(CD_CPD AS INT) AS CD_CPD
	,CAST(CD_ANGARIADOR AS INT) AS CD_ANGARIADOR
	,CAST(CD_AGENC_PROD AS INT) AS CD_AGENC_PROD
	,CAST(NR_INSPETORIA AS INT) AS NR_INSPETORIA
	,CAST(CD_EVENTO AS INT) AS CD_EVENTO
	,dbo.fn_TrataData(DT_ULTIMO_EVENTO) AS DT_ULTIMO_EVENTO
	,DS_ULTIMO_EVENTO      
	,dbo.fn_TrataData(DT_PRIMEIRO_EVENTO)  AS DT_PRIMEIRO_EVENTO
	,dbo.fn_TrataData(DT_ULTIMA_PENDENCIA) AS DT_ULTIMA_PENDENCIA
	,DS_ULTIMA_PENDENCIA      
	,dbo.fn_TrataData(DT_ULTIMA_REJEICAO) AS DT_ULTIMA_REJEICAO
	,DS_ULTIMA_REJEICAO      
	,dbo.fn_TrataData(DT_NASCIMENTO) AS DT_NASCIMENTO
	,CAST(ESTADO_CIVIL AS INT) AS ESTADO_CIVIL
	,CASE WHEN ISNUMERIC(FILHOS) = 1 THEN NULL ELSE FILHOS END FILHOS      
	,FXETARIA_FILHOS
	,IN_GARAGEM
	,IN_OUTROS_VEICULOS
	,SEXO
	,TIPO_PESSOA
	,CD_SUPERVISOR01
	,CD_SUPERVISOR02
	,CD_SUPERVISOR03
	,CD_SUPERVISOR04
	,CD_SUPERVISOR05
	,CD_SUPERVISOR06
	,CD_SUPERVISOR07
	,CD_SUPERVISOR08
	,CD_SUPERVISOR09
	,CD_SUPERVISOR10
	,CAST(QT_TRANS_PROP AS INT) AS QT_TRANS_PROP
	,CAST(CD_ALERTA01 AS INT) AS CD_ALERTA01
	,USER_LIBER01
	,LIBRC_CONTR01
	,dbo.fn_TrataData(DATA_LIBER01) AS DATA_LIBER01
	,CAST(NIVEL_ALCADA01 AS INT) AS NIVEL_ALCADA01
	,CAST(CD_ALERTA02 AS INT) AS CD_ALERTA02
	,USER_LIBER02
	,LIBRC_CONTR02
	,dbo.fn_TrataData(DATA_LIBER02) AS DATA_LIBER02
	,CAST(NIVEL_ALCADA02 AS INT) AS NIVEL_ALCADA02
	,CAST(CD_ALERTA03 AS INT) AS CD_ALERTA03
	,USER_LIBER03
	,LIBRC_CONTR03
	,dbo.fn_TrataData(DATA_LIBER03)  AS DATA_LIBER03
	,CAST(NIVEL_ALCADA03 AS INT) AS NIVEL_ALCADA03
	,CAST(CD_ALERTA04 AS INT) AS CD_ALERTA04
	,USER_LIBER04
	,LIBRC_CONTR04
	,dbo.fn_TrataData(DATA_LIBER04) AS DATA_LIBER04
	,CAST(NIVEL_ALCADA04 AS INT) AS NIVEL_ALCADA04
	,CAST(CD_ALERTA05 AS INT) AS CD_ALERTA05
	,USER_LIBER05
	,LIBRC_CONTR05
	,dbo.fn_TrataData(DATA_LIBER05) AS DATA_LIBER05
	,CAST(NIVEL_ALCADA05 AS INT) AS NIVEL_ALCADA05
	,CAST(CD_ALERTA06 AS INT) AS CD_ALERTA06
	,USER_LIBER06
	,LIBRC_CONTR06
	,dbo.fn_TrataData(DATA_LIBER06) AS DATA_LIBER06
	,CAST(NIVEL_ALCADA06 AS INT) AS NIVEL_ALCADA06
	,CAST(CD_ALERTA07 AS INT) AS CD_ALERTA07
	,USER_LIBER07
	,LIBRC_CONTR07
	,dbo.fn_TrataData(DATA_LIBER07) AS DATA_LIBER07
	,CAST(NIVEL_ALCADA07 AS INT) AS NIVEL_ALCADA07
	,CAST(CD_ALERTA08 AS INT) AS CD_ALERTA08
	,USER_LIBER08
	,LIBRC_CONTR08
	,dbo.fn_TrataData(DATA_LIBER08) AS DATA_LIBER08
	,CAST(NIVEL_ALCADA08 AS INT) AS NIVEL_ALCADA08
	,CAST(CD_ALERTA09 AS INT) AS CD_ALERTA09
	,USER_LIBER09
	,LIBRC_CONTR09
	,dbo.fn_TrataData(DATA_LIBER09) AS DATA_LIBER09
	,CAST(NIVEL_ALCADA09 AS INT) AS NIVEL_ALCADA09
	,CAST(CD_ALERTA10 AS INT) AS CD_ALERTA10
	,USER_LIBER10
	,LIBRC_CONTR10
	,dbo.fn_TrataData(DATA_LIBER10) AS DATA_LIBER10
	,CAST(NIVEL_ALCADA10 AS INT) AS NIVEL_ALCADA10
	,CAST(CD_ALERTA11 AS INT) AS CD_ALERTA11
	,USER_LIBER11
	,LIBRC_CONTR11
	,dbo.fn_TrataData(DATA_LIBER11) AS DATA_LIBER11
	,CAST(NIVEL_ALCADA11 AS INT) AS NIVEL_ALCADA011
	,CAST(CD_ALERTA12 AS INT) AS CD_ALERTA12
	,USER_LIBER12
	,LIBRC_CONTR12
	,dbo.fn_TrataData(DATA_LIBER12) AS DATA_LIBER12
	,CAST(NIVEL_ALCADA12 AS INT) AS NIVEL_ALCADA12
	,CAST(CD_ALERTA13 AS INT) AS CD_ALERTA13
	,USER_LIBER13
	,LIBRC_CONTR13
	,dbo.fn_TrataData(DATA_LIBER13) AS DATA_LIBER13
	,CAST(NIVEL_ALCADA13 AS INT) AS NIVEL_ALCADA13
	,CAST(CD_ALERTA14 AS INT) AS CD_ALERTA14
	,USER_LIBER14
	,LIBRC_CONTR14
	,dbo.fn_TrataData(DATA_LIBER14) AS DATA_LIBER14
	,CAST(NIVEL_ALCADA14 AS INT) AS NIVEL_ALCADA14
	,CAST(CD_ALERTA15 AS INT) AS CD_ALERTA15
	,USER_LIBER15
	,LIBRC_CONTR15
	,dbo.fn_TrataData(DATA_LIBER15) AS DATA_LIBER15
	,CAST(NIVEL_ALCADA15 AS INT) AS NIVEL_ALCADA15
	,CAST(CD_ALERTA16 AS INT) AS CD_ALERTA16
	,USER_LIBER16
	,LIBRC_CONTR16
	,dbo.fn_TrataData(DATA_LIBER16) AS DATA_LIBER16
	,CAST(NIVEL_ALCADA16 AS INT) AS NIVEL_ALCADA16
	,CAST(CD_ALERTA17 AS INT) AS CD_ALERTA17
	,USER_LIBER17
	,LIBRC_CONTR17
	,dbo.fn_TrataData(DATA_LIBER17) AS DATA_LIBER17
	,CAST(NIVEL_ALCADA17 AS INT) AS NIVEL_ALCADA17
	,CAST(CD_ALERTA18 AS INT) AS CD_ALERTA18
	,USER_LIBER18
	,LIBRC_CONTR18
	,dbo.fn_TrataData(DATA_LIBER18) AS DATA_LIBER18
	,CAST(NIVEL_ALCADA18 AS INT) AS NIVEL_ALCADA18
	,CAST(CD_ALERTA19 AS INT) AS CD_ALERTA19
	,USER_LIBER19
	,LIBRC_CONTR19
	,dbo.fn_TrataData(DATA_LIBER19) AS DATA_LIBER19
	,CAST(NIVEL_ALCADA19 AS INT) AS NIVEL_ALCADA19
	,CAST(CD_ALERTA20 AS INT) AS CD_ALERTA20
	,USER_LIBER20
	,LIBRC_CONTR20
	,dbo.fn_TrataData(DATA_LIBER20) AS DATA_LIBER20
	,CAST(NIVEL_ALCADA20 AS INT) AS NIVEL_ALCADA20                  
	,IN_CCB
	,IN_AVISTA
	,CAST(CD_MOTIVO01 AS INT) AS CD_MOTIVO01      
	,CASE WHEN DS_MOTIVO01 LIKE 'EMISS¶O DE PRO%' THEN 'EMISSAO DE PROPOSTA' 
		  WHEN DS_MOTIVO01 LIKE 'RENOVA€AO DE APO%' THEN 'RENOVACAO DE APOLICE'
	      ELSE DS_MOTIVO01 END AS DS_MOTIVO01
	,CAST(CD_MOTIVO02 AS INT) AS CD_MOTIVO02 
	,DS_MOTIVO02
	,CAST(CD_MOTIVO03 AS INT) AS CD_MOTIVO03
	,DS_MOTIVO03
	,CAST(CD_MOTIVO04 AS INT) AS CD_MOTIVO04
	,DS_MOTIVO04
	,CAST(CD_MOTIVO05 AS INT) AS CD_MOTIVO05
	,DS_MOTIVO05
	,CAST(CD_MOTIVO06 AS INT) AS CD_MOTIVO06
	,DS_MOTIVO06
	,CAST(CD_MOTIVO07 AS INT) AS CD_MOTIVO07
	,DS_MOTIVO07
	,CAST(CD_MOTIVO08 AS INT) AS CD_MOTIVO08
	,DS_MOTIVO08
	,CAST(CD_MOTIVO09 AS INT) AS CD_MOTIVO09
	,DS_MOTIVO09
	,CAST(CD_MOTIVO10 AS INT) AS CD_MOTIVO10
	,DS_MOTIVO10
	,CAST(CLASSE_BONUS AS INT) AS CLASSE_BONUS
	,CIND_SEGUR_RESID
	,CAST(PDESC_ESPCL_CONCD AS INT) AS PDESC_ESPCL_CONCD
	,CAST(CD_ANTI_FURTO AS INT) AS CD_ANTI_FURTO
	,DS_CARROCERIA
	,CAST(CD_EQUIPAMENTO01 AS INT) AS CD_EQUIPAMENTO01
	,CAST(CD_EQUIPAMENTO02 AS INT) AS CD_EQUIPAMENTO02
	,CAST(CD_EQUIPAMENTO03 AS INT) AS CD_EQUIPAMENTO03
	,CAST(CD_EQUIPAMENTO04 AS INT) AS CD_EQUIPAMENTO04
	,CAST(CD_EQUIPAMENTO05 AS INT) AS CD_EQUIPAMENTO05
	,CAST(CD_EQUIPAMENTO06 AS INT) AS CD_EQUIPAMENTO06
	,CAST(CD_EQUIPAMENTO07 AS INT) AS CD_EQUIPAMENTO07
	,CAST(CD_EQUIPAMENTO08 AS INT) AS CD_EQUIPAMENTO08
	,CAST(CD_EQUIPAMENTO09 AS INT) AS CD_EQUIPAMENTO09
	,CAST(CD_EQUIPAMENTO10 AS INT) AS CD_EQUIPAMENTO10
	,CAST(CD_ACESSORIO01 AS INT) AS CD_ACESSORIO01
	,CAST(CD_ACESSORIO02 AS INT) AS CD_ACESSORIO02
	,CAST(CD_ACESSORIO03 AS INT) AS CD_ACESSORIO03
	,CAST(CD_ACESSORIO04 AS INT) AS CD_ACESSORIO04
	,CAST(CD_ACESSORIO05 AS INT) AS CD_ACESSORIO05
	,CAST(CD_ACESSORIO06 AS INT) AS CD_ACESSORIO06
	,CAST(CD_ACESSORIO07 AS INT) AS CD_ACESSORIO07
	,CAST(CD_ACESSORIO08 AS INT) AS CD_ACESSORIO08
	,CAST(CD_ACESSORIO09 AS INT) AS CD_ACESSORIO09
	,CAST(CD_ACESSORIO10 AS INT) AS CD_ACESSORIO10
	,dbo.fn_TrataData(DT_SAIDA_CONC) AS DT_SAIDA_CONC
	,IN_CHASSI_REM
	,IN_VEIC_TRANSF
	,IN_SUPER_AUTO
	,CAST(CLASSE_BONUS_ANT AS INT) AS CLASSE_BONUS_ANT
	,CAST(NR_SINISTRO AS INT) AS NR_SINISTRO
	,CASE WHEN CD_PROCED_VEIC = 1 THEN 'PROCED NAC' 
		  WHEN CD_PROCED_VEIC = 2 THEN 'PROCED EST' 
		  WHEN CD_PROCED_VEIC = 3 THEN 'PROCED NAC EST' END AS CD_PROCED_VEIC
	,CAST(NR_PROPOSTA_ORIG AS INT) AS NR_PROPOSTA_ORIG
	,dbo.fn_TrataData(DT_EFET_PROP_ORIG) AS DT_EFET_PROP_ORIG
	,CD_USUARIO_SOL
	,CAST(NR_ITENS_FROTA AS INT) AS NR_ITENS_FROTA
	,CIND_NOVA_TARIFA
	,CAST(CD_REGIAO_TARIFARIA AS INT) AS CD_REGIAO_TARIFARIA
	,VERSAO_TARIFA
	,CAST(NR_APOLICE AS INT) AS NR_APOLICE
	,dbo.fn_TrataMoney(VL_PREMIO_RCF_DM) AS VL_PREMIO_RCF_DM
	,dbo.fn_TrataMoney(VL_PREMIO_RCF_DC) AS VL_PREMIO_RCF_DC
	,dbo.fn_TrataMoney(VL_PREMIO_RCF_DMO) AS VL_PREMIO_RCF_DMO
	,dbo.fn_TrataMoney(VL_PREMIO_RCF_GU) AS VL_PREMIO_RCF_GU
	,dbo.fn_TrataMoney(VL_PREMIO_APP_MO) AS VL_PREMIO_APP_MO
	,dbo.fn_TrataMoney(VL_PREMIO_APP_INV) AS VL_PREMIO_APP_INV
	,CAST(TIPO_VEICULO AS INT) AS TIPO_VEICULO
	,dbo.fn_TrataMoney(VL_PREMIO_CASCO) AS VL_PREMIO_CASCO
	,dbo.fn_TrataMoney(VL_PREMIO_DESP_EXT) AS VL_PREMIO_DESP_EXT
	,dbo.fn_TrataMoney(VL_PREMIO_CARROCERIA) AS VL_PREMIO_CARROCERIA
	,dbo.fn_TrataMoney(VL_PREMIO_EQUIP) AS VL_PREMIO_EQUIP
	,dbo.fn_TrataMoney(VL_PREMIO_ACCESS) AS VL_PREMIO_ACCESS
	,dbo.fn_TrataMoney(VL_PREMIO_DIARIAS) AS VL_PREMIO_DIARIAS
	,dbo.fn_TrataMoney(VL_PREMIO_KIT_GAS) AS VL_PREMIO_KIT_GAS
	,dbo.fn_TrataMoney(VL_SERVICO_DIA_NOITE) AS VL_SERVICO_DIA_NOITE
	,dbo.fn_TrataMoney(VL_SERVICO_CARRO_RES) AS VL_SERVICO_CARRO_RES
	,dbo.fn_TrataMoney(VL_SERVICO_VIDROS) AS VL_SERVICO_VIDROS
	,CAST(TIPO_CLIENTE AS INT) AS TIPO_CLIENTE
	,CAST(CD_FRANQUIA AS INT) AS CD_FRANQUIA
	,FLG_RENOVA_PROPRIA
	,CAST(CD_RELACAO_SEG_PROP AS INT) AS CD_RELACAO_SEG_PROP
	,CASE WHEN TP_CANCELAMENTO = 'P' THEN 'FALTA DE PAGAMENTO'
		  WHEN TP_CANCELAMENTO = 'M' THEN 'FALTA DE MOVIMENTACAO'
		  WHEN TP_CANCELAMENTO = 'O' THEN 'OUTROS' END AS TP_CANCELAMENTO
	,IN_COMODATO
	,CAST(CD_SEMI_REBOQUE AS INT) AS CD_SEMI_REBOQUE
	,dbo.fn_TrataMoney(VL_LMI_BLINDAGEM) AS VL_LMI_BLINDAGEM
	,dbo.fn_TrataMoney(VL_PREMIO_BLINDAGEM) AS VL_PREMIO_BLINDAGEM
	,dbo.fn_TrataMoney(VL_LMI_KITGAS) AS VL_LMI_KITGAS
	,dbo.fn_TrataMoney(VL_FRANQUIA_CASCO) AS VL_FRANQUIA_CASCO
	,dbo.fn_TrataMoney(VL_FRANQUIA_KITGAS) AS VL_FRANQUIA_KITGAS
	,CAST(PDESC_CRIVO AS INT) AS PDESC_CRIVO
	,NOPER_CRIVO
	,CAST(CRETOR_CRIVO AS INT) AS CRETOR_CRIVO
	,CIND_RCUSA_COTAC
	,CIND_SBCAO_CRIVO
	,CAST(PDESC_LIM_CRIVO AS INT) AS PDESC_LIM_CRIVO
	,CAST(QPTO_OPER_CRIVO AS INT) AS QPTO_OPER_CRIVO
	,CAST(CCLASF_SERASA_OPER AS INT) AS CCLASF_SERASA_OPER
	,COBR_VIA_CCBS
	,CIND_LIBER_CCB
	,CAST(CD_USO_VEIC AS INT) AS CD_USO_VEIC
	,CAST(CD_COMBUST AS INT) AS CD_COMBUST
	,CAST(CCONTX_OPER_CRIVO AS INT) AS CCONTX_OPER_CRIVO
	,CAST(STUFF(PC_COMISS_AUTO,LEN(PC_COMISS_AUTO) - 1,0,'.') AS FLOAT) AS PC_COMISS_AUTO
	,CAST(STUFF(PC_COMISS_RCF,LEN(PC_COMISS_RCF) - 1,0,'.') AS FLOAT) AS PC_COMISS_RCF    
	,CAST(STUFF(PC_COMISS_APP,LEN(PC_COMISS_APP) - 1,0,'.') AS FLOAT) AS PC_COMISS_APP            
	,IN_REVENDA
	,CAST(CGRP_REVDA_VEIC AS INT) AS CGRP_REVDA_VEIC      
	,CASE WHEN ISDATE(CONVERT(VARCHAR(19),DINIC_VGCIA_GRP,120))=0 THEN NULL ELSE CONVERT(VARCHAR(19),DINIC_VGCIA_GRP,120) END AS DINIC_VGCIA_GRP
	,CAST(CSEQ_REVDA_VEIC AS INT) AS CSEQ_REVDA_VEIC
	,IN_CARTAO
	,CAST(NR_CARTAO_CREDITO AS BIGINT) AS NR_CARTAO_CREDITO
	,CAST(COPER_CATAO AS INT) AS COPER_CATAO
	,CAST(CVALDD_CATAO_CREDT AS INT) AS CVALDD_CATAO_CREDT
	,CASE WHEN APLICATIVO = 'SAB EMISS¶O' THEN 'SAB EMISSAO' ELSE APLICATIVO END AS APLICATIVO
	,CAST(CCNPJ_CRRTR AS BIGINT) AS CCNPJ_CRRTR
	,CAST(CNRO_LOTE_FROTA AS INT) AS CNRO_LOTE_FROTA
	,CODIGO_CI
	,CSEXO_PPRIE_VEIC
	,dbo.fn_TrataData(DNASC_PPRIE_VEIC) AS DNASC_PPRIE_VEIC
	,CASE WHEN CEST_CVIL_PPRIE = 1 THEN 'SOLTEIRO-OUTROS' WHEN CEST_CVIL_PPRIE = 2 THEN 'CASADO' END AS CEST_CVIL_PPRIE
	,CAST(CCONTR_ESPCL AS INT) AS CCONTR_ESPCL
	,CIND_MESA_NEGOC
	,CAST(PROPOSTA_ANT AS INT) AS PROPOSTA_ANT
	,CAST(CTPO_FUNC_PBLIC AS INT) AS CTPO_FUNC_PBLIC
	,CIND_LIBR_MOTVO
	,CIND_ACEIT_RESTR
	,CIND_SEGURO_CORRETOR
	,CAST(COPCAO_SEGUR_RESID AS INT) AS COPCAO_SEGUR_RESID
	,CAST(COD_PRESTADORA AS INT) AS COD_PRESTADORA
	,IN_PPV
	,CASE WHEN TIPO_CONTA = 1 THEN 'CONTA CORRENTE' WHEN TIPO_CONTA = 2 THEN 'CONTA POUPANCA' END AS TIPO_CONTA
	,CAST(BANCO_CRED AS INT) AS BANCO_CRED
	,CAST(AGENCIA_CRED AS INT) AS AGENCIA_CRED
	,CAST(NR_CONTA_CRED AS BIGINT) AS NR_CONTA_CRED
	,DV_CONTA_CRED
	,CAST(VFATOR_AGRVO_LNEAR AS INT) AS VFATOR_AGRVO_LNEAR
	,CAST(CD_SUSEP14 AS BIGINT) AS CD_SUSEP14
	,USUARIO_COTACAO
	,CAST(CPF_CNPJ_COTACAO AS BIGINT) AS CPF_CNPJ_COTACAO
	,PESSOA_COTACAO
	,EMAIL_SEGURADO
	,TP_UTIL_FONE_RES
	,CAST(NR_DDD_RES AS INT) AS NR_DDD_RES
	,CAST(NR_FONE_RES AS INT) AS NR_FONE_RES
	,TP_UTIL_FONE_COM
	,CAST(NR_DDD_COM AS INT) AS NR_DDD_COM
	,CAST(NR_FONE_COM AS INT) AS NR_FONE_COM
	,TP_UTIL_FONE_CEL
	,CAST(NR_DDD_CEL AS INT) AS NR_DDD_CEL
	,CAST(NR_FONE_CEL AS INT) AS NR_FONE_CEL
	,TP_UTIL_FONE_CONL
	,CAST(NR_DDD_CON AS INT) AS NR_DDD_CON
	,CAST(NR_FONE_CON AS INT) AS NR_FONE_CON
	,NM_FONE_CON
	,CAST(DESC_DCE AS INT) AS DESC_DCE
	,CAST(CNEGOC_DCE AS INT) AS CNEGOC_DCE
	,CAST(CTPO_CEN_DEC AS INT) AS CTPO_CEN_DEC
	,CAST(PREM_LIQ_RESID AS INT) AS PREM_LIQ_RESID
	,CAST(CTPO_PRFIL_PROPN AS INT) AS CTPO_PRFIL_PROPN
	,CIND_PPRIE_VEIC
	,CIND_CNDOR_PRINC
	,ICNDOR
	,CAST(CCPF_PSSOA_CNDOR AS BIGINT) AS CCPF_PSSOA_CNDOR
	,dbo.fn_TrataData(DNASC_CNDOR) AS DNASC_CNDOR
	,CSEXO_CNDOR
	,CASE WHEN CEST_CVIL_CNDOR = 1 THEN 'SOLTEIRO OUTROS' WHEN CEST_CVIL_CNDOR = 2 THEN 'CASADO' END AS CEST_CVIL_CNDOR
	,CAST(CTPO_OUTRO_CNDOR AS INT) AS CTPO_OUTRO_CNDOR
	,CAST(CTPO_GARAG_PNOIT AS INT) AS CTPO_GARAG_PNOIT
	,CAST(CATVDD_PRINC_CNDOR AS INT) AS CATVDD_PRINC_CNDOR
	,CAST(CRAMO_ATV_PRINC_CNDOR AS INT) AS CRAMO_ATV_PRINC_CNDOR
	,CAST(CUTILZ_VEIC_TRAB AS INT) AS CUTILZ_VEIC_TRAB
	,CAST(CLOC_FIXO_TRAB AS INT) AS CLOC_FIXO_TRAB
	,CAST(NCEP_LOC_TRAB AS INT) AS NCEP_LOC_TRAB
	,CAST(CTPO_GARAG_LOC_TRAB AS INT) AS CTPO_GARAG_LOC_TRAB
	,CAST(CUTILZ_VEIC_STUDO AS INT) AS CUTILZ_VEIC_STUDO
	,CAST(CLOC_FIXO_STUDO AS INT) AS CLOC_FIXO_STUDO
	,CAST(NCEP_LOC_STUDO AS INT) AS NCEP_LOC_STUDO
	,CAST(CTPO_GARAG_LOC_STUDO AS INT) AS CTPO_GARAG_LOC_STUDO
	,CAST(CFAIXA_KM AS INT) AS CFAIXA_KM
	,dbo.fn_TrataMoney(VL_PREMIO_RCF) AS VL_PREMIO_RCF
	,dbo.fn_TrataMoney(VL_PREMIO_APP) AS VL_PREMIO_APP
	,CAST(CD_VEICULO_NOVO AS INT) AS CD_VEICULO_NOVO
	,CAST(CD_MOLICAR AS INT) AS CD_MOLICAR
	,IN_ELETRO_HIDRAULICA
	,IN_ELETRICA
	,IN_OPC_OUTROS
	,CIND_CATAO_BDSCO
	,CAST(NR_ENDOSSO AS INT) AS NR_ENDOSSO
	,dbo.fn_TrataMoney(VL_PREM_TAR_CASCO) AS VL_PREM_TAR_CASCO
	,dbo.fn_TrataMoney(VL_PREM_TAR_ACESS) AS VL_PREM_TAR_ACESS
	,dbo.fn_TrataMoney(VL_PREM_TAR_CARROC) AS VL_PREM_TAR_CARROC
	,dbo.fn_TrataMoney(VL_PREM_TAR_EQUIP) AS VL_PREM_TAR_EQUIP
	,dbo.fn_TrataMoney(VL_PREM_TAR_BLIND) AS VL_PREM_TAR_BLIND
	,dbo.fn_TrataMoney(VL_PREM_TAR_CARRO_RES) AS VL_PREM_TAR_CARRO_RES
	,dbo.fn_TrataMoney(VL_PREM_TAR_DESP_EXT) AS VL_PREM_TAR_DESP_EXT
	,dbo.fn_TrataMoney(VL_PREM_TAR_KITGAS) AS VL_PREM_TAR_KITGAS
	,dbo.fn_TrataMoney(VL_PREM_TAR_DIARIAS) AS VL_PREM_TAR_DIARIAS
	,dbo.fn_TrataMoney(VL_PREM_TAR_ADN) AS VL_PREM_TAR_ADN
	,dbo.fn_TrataMoney(VL_PREM_TAR_VIDROS) AS VL_PREM_TAR_VIDROS
	,dbo.fn_TrataMoney(VL_PREM_TAR_AUTO) AS VL_PREM_TAR_AUTO
	,dbo.fn_TrataMoney(VL_PREM_TAR_DM) AS VL_PREM_TAR_DM
	,dbo.fn_TrataMoney(VL_PREM_TAR_DC) AS VL_PREM_TAR_DC
	,dbo.fn_TrataMoney(VL_PREM_TAR_DMO) AS VL_PREM_TAR_DMO
	,dbo.fn_TrataMoney(VL_PREM_TAR_GU) AS VL_PREM_TAR_GU
	,dbo.fn_TrataMoney(VL_PREM_TAR_RCF) AS VL_PREM_TAR_RCF
	,dbo.fn_TrataMoney(VL_PREM_TAR_MORTE) AS VL_PREM_TAR_MORTE
	,dbo.fn_TrataMoney(VL_PREM_TAR_INVAL) AS VL_PREM_TAR_INVAL
	,dbo.fn_TrataMoney(VL_PREM_TAR_APP) AS VL_PREM_TAR_APP
	,dbo.fn_TrataMoney(VL_PREM_TAR_TOTAL) AS VL_PREM_TAR_TOTAL
	,dbo.fn_TrataData(DT_CONCIL_VP) AS DT_CONCIL_VP
	,dbo.fn_TrataData(DT_TRANSM_VP) AS DT_TRANSM_VP
	,CAST(NR_VISTORIA AS INT) AS NR_VISTORIA
	,CD_SITUACAO_VP
	,CAST(CD_EMPR_VIST AS INT) AS CD_EMPR_VIST
	,IND_VP_GERADA_CALC
	,IND_VP_REALIZ
	,CAST(CD_OCUP_PRINC AS INT) AS CD_OCUP_PRINC
	,IND_CERTF_DIGITAL
	,dbo.fn_TrataMoney(VL_PREMIO_DCE) AS VL_PREMIO_DCE
	,dbo.fn_TrataMoney(VL_DESC_DCE) AS VL_DESC_DCE
	,dbo.fn_TrataMoney(VL_PREMIO_CAPIT_RES) AS VL_PREMIO_CAPIT_RES
	,dbo.fn_TrataMoney(VL_PREMIO_ADN_RES) AS VL_PREMIO_ADN_RES
	,CAST(NR_LOGRAD AS INT) AS NR_LOGRAD
	,CAST(NR_LOGRAD_RISCO AS INT) AS NR_LOGRAD_RISCO
	,CAST(CMOD_TRFIO AS INT) AS CMOD_TRFIO
	,CAST(CNOVA_RGIAO_RISCO AS INT) AS CNOVA_RGIAO_RISCO
	,dbo.fn_TrataMoney(VPRMIO_PERDA_PCIAL) AS VPRMIO_PERDA_PCIAL
	,dbo.fn_TrataMoney(VPRMIO_PERDA_TOT) AS VPRMIO_PERDA_TOT
	,dbo.fn_TrataMoney(VPRMIO_ROUBO_FURTO) AS VPRMIO_ROUBO_FURTO
	,dbo.fn_TrataMoney(VSERVC_ADN) AS VSERVC_ADN
	,dbo.fn_TrataMoney(VSERVC_VIDRO) AS VSERVC_VIDRO
	,dbo.fn_TrataMoney(VSERVC_CAR_RES) AS VSERVC_CAR_RES
	,CAST(CCLASS_BONUS_PP AS INT) AS CCLASS_BONUS_PP
	,CAST(CCLASS_BONUS_PT AS INT) AS CCLASS_BONUS_PT
	,CAST(CCLASS_BONUS_RF AS INT) AS CCLASS_BONUS_RF
	,CAST(CSIT_CCB AS INT) AS CSIT_CCB
	,CAST(CCLASS_BONUS_DM AS INT) AS CCLASS_BONUS_DM                  
	,FILLER
FROM [tbBR_tab_tmp_NASA]



